Repository scratchfoundation/scratch-gui, pull requests merged in 2018-12, with the labels that each got.

#3917 Update scratch-l10n dependency
  package.json
Labels: localization, pr - good to merge

#3916 Cloud Variable Rate Limit
  package.json
  src/lib/cloud-provider.js
Labels: pr - good to merge

#3925 Include polyfill for promise.finally so Edge can load projects
  src/playground/index.jsx
Labels: pr - good to merge

#3927 Fix stage wrapper not setting dir="ltr/rtl" property, buttons look wrong
  src/components/gui/gui.jsx
  src/components/stage-wrapper/stage-wrapper.jsx
Labels: pr - good to merge

#3931 Has cloud permission
  src/lib/cloud-manager-hoc.jsx
  test/unit/util/cloud-manager-hoc.test.jsx
Labels: pr - good to merge

#3944 [Master] sound library update
  src/lib/libraries/sounds.json
Labels: hotfix, pr - good to merge

#3817 Update videoState to match default in rendered-target
  src/lib/default-project/project-data.js
Labels: pr - good to merge

#3946 Feature/3942 embed project
  src/components/stage-header/stage-header.css
  src/components/stage-header/stage-header.jsx
  src/containers/stage-header.jsx
  src/index.js
  src/reducers/gui.js
  src/reducers/mode.js
Labels: pr - good to merge

#3961 Fix error logging when workspace fails to update
  src/containers/blocks.jsx
Labels: pr - good to merge

#3960 Do not show cloud variable option in list modal.
  src/containers/blocks.jsx
Labels: pr - good to merge

#3966 if in LoadingState.SHOWING_WITHOUT_ID, don't transition to default project
  src/reducers/project-state.js
Labels: pr - good to merge

#3972 Bind vm project_start event to passed in onGreenFlag prop
  src/lib/vm-listener-hoc.jsx
  test/unit/util/vm-listener-hoc.test.jsx
Labels: pr - good to merge

#3965 handle the onRemixing prop from www
  src/lib/project-saver-hoc.jsx
  test/unit/util/project-saver-hoc.test.jsx
Labels: pr - good to merge

#3977 Updated Scratch Cat!
  src/lib/default-project/project-data.js
  src/lib/libraries/costumes.json
  src/lib/libraries/sprites.json
Labels: pr - good to merge

#3979 Change "See Community" to "See Project Page"
  src/components/menu-bar/community-button.jsx
Labels: pr - good to merge

#3973 Hidden tutorial library items for LEGO WeDo 2.0 and EV3
  src/components/library-item/library-item.css
  src/components/library-item/library-item.jsx
  src/components/library/library.jsx
  src/containers/tips-library.jsx
  src/lib/libraries/decks/index.jsx
Labels: pr - good to merge

#3981 update the scratch-vm we use in package.json
  package.json
Labels: pr - good to merge

#3974 translate new project confirm alert
  src/components/menu-bar/menu-bar.jsx
Labels: pr - good to merge

#3937 use blue creating screen for new projects; revised alert text for copy/remix
  src/components/gui/gui.jsx
  src/components/loader/loader.jsx
  src/lib/alerts/index.jsx
  src/lib/project-saver-hoc.jsx
  src/reducers/project-state.js
  test/unit/reducers/alerts-reducer.test.js
  test/unit/util/project-saver-hoc.test.jsx
Labels: pr - good to merge

#3913 warn user if they leave project that's not saved
  src/lib/project-saver-hoc.jsx
  test/integration/sounds.test.js
Labels: pr - needs work

#3991 Use the correct font fallbacks for navbar save messages
  src/components/alerts/inline-message.css
Labels: pr - needs review

#3993 Fix an issue where switching player to editor mode caused "Save Now".
  src/lib/vm-listener-hoc.jsx
Labels: pr - good to merge

#3992 Only show the `SaveStatus` component for people who can save
  src/components/menu-bar/menu-bar.jsx
Labels: pr - needs review

#3999 Add deploy step to push translations in travis
  .travis.yml
Labels: pr - good to merge

#3998 Force margin on inputs which is reset by normalizer in www
  src/components/custom-procedures/custom-procedures.css
  src/components/prompt/prompt.css
Labels: pr - good to merge

#4004 Do not open a new tab when clicking scratch logo
  src/components/menu-bar/menu-bar.jsx
Labels: pr - good to merge

#4009 Unskip integration test for #3608.
  package.json
  test/integration/sprites.test.js
Labels: pr - needs review

#4015 Manually upload projects using xhr, rather than scratch-storage
  src/lib/project-saver-hoc.jsx
Labels: pr - good to merge

#4012 after loading project, switch to code tab
  src/lib/project-fetcher-hoc.jsx
  src/reducers/project-state.js
  test/integration/project-loading.test.js
Labels: pr - good to merge

#4020 Show error screen when project cannot be loaded
  src/lib/project-fetcher-hoc.jsx
  test/integration/project-loading.test.js
Labels: pr - good to merge

#3969 removed various props from children; renamed prop to be more consistent
  src/lib/project-fetcher-hoc.jsx
  src/lib/project-saver-hoc.jsx
  src/lib/vm-listener-hoc.jsx
  src/lib/vm-manager-hoc.jsx
  src/playground/render-gui.jsx
Labels: pr - good to merge

#4041 Update WeDo tutorial video
  src/lib/libraries/decks/index.jsx
Labels: pr - good to merge

#4036 Make the git links in the README consistent
  README.md
Labels: pr - good to merge

#4031 Make mousedown on the stage blur inputs, with @picklesrus
  src/containers/stage.jsx
Labels: pr - good to merge

#4044 Update sprite library with new assets
  src/lib/libraries/sprites.json
Labels: pr - good to merge

#4035 admins will see author credits, not title editing field, in editor
  src/components/menu-bar/menu-bar.jsx
Labels: pr - good to merge

#4024 Fix empty <MenuSection>
  src/components/menu-bar/menu-bar.jsx
Labels: pr - needs review

#4051 revised alerts and spinner styling
  src/components/alerts/alert.css
  src/components/alerts/alert.jsx
  src/components/alerts/alerts.css
  src/components/alerts/alerts.jsx
  src/components/alerts/inline-message.jsx
  src/components/gui/gui.css
  src/components/spinner/spinner.css
  src/components/spinner/spinner.jsx
Labels: pr - good to merge

#4071 Try to always keep the tutorial in view despite screen height
  src/components/cards/cards.jsx
Labels: pr - good to merge

#4054 Give max-width to sprite tiles to prevent long names issue
  src/components/backpack/backpack.css
  src/components/sprite-selector/sprite-selector.css
Labels: pr - good to merge

#3984 Treat defaultValue from Blockly prompts properly
  src/components/prompt/prompt.jsx
  src/containers/blocks.jsx
  src/containers/prompt.jsx
Labels: pr - good to merge

#4033 close file menu on uploading sb file; don't close file menu twice
  src/components/menu-bar/menu-bar.jsx
  src/containers/sb-file-uploader.jsx
Labels: pr - good to merge

#4048 Randomize Sprite Positions
  src/containers/sprite-library.jsx
  src/containers/target-pane.jsx
  src/lib/file-uploader.js
  src/lib/randomize-sprite-position.js
Labels: pr - good to merge

#4089 Actually use the showPreviewInfo prop to show the preview modal
  src/lib/app-state-hoc.jsx
Labels: pr - good to merge

#4092 Revert 4035 admin sees author
  src/components/menu-bar/menu-bar.jsx
  test/integration/menu-bar.test.js
Labels: pr - good to merge

#3866 only prompt user to save if project has changed and won’t autosave
  src/components/menu-bar/menu-bar.jsx
  test/integration/project-loading.test.js
Labels: pr - good to merge

#4087 Use 3.0 routes for GETs
  src/lib/storage.js
  test/integration/examples.test.js
Labels: pr - good to merge

#4111 render vm when requesting project thumbnail, so it is set immediately
  src/lib/project-saver-hoc.jsx
Labels: pr - needs review

#4090 Call add costume from library to fix bounding box issues with some library sprites
  src/containers/costume-library.jsx
  src/containers/costume-tab.jsx
Labels: pr - good to merge

#4132 Remove unnecessary console logs that occur when sending and receiving cloud messages.
  src/lib/cloud-provider.js
Labels: pr - good to merge

#4134 When user uploads project file, project will auto-save before loading
  src/containers/sb-file-uploader.jsx
  src/lib/vm-manager-hoc.jsx
  src/reducers/project-state.js
  test/unit/reducers/project-state-reducer.test.js
Labels: pr - good to merge

#4115 Fix "TouchEvent is not defined" error
  src/containers/stage.jsx
Labels: pr - good to merge

#4081 Make the requiredProjectId work with the online editor
  src/containers/tips-library.jsx
Labels: critical, pr - good to merge

#4113 Add a helper function to check if GUI is running in Scratch Desktop
  src/containers/gui.jsx
  src/containers/tips-library.jsx
  src/lib/isScratchDesktop.js
  src/playground/render-gui.jsx
Labels: critical, pr - good to merge

#4149 Sprite and costume library fixes
  src/lib/libraries/costumes.json
  src/lib/libraries/sounds.json
  src/lib/libraries/sprites.json
Labels: pr - needs work

#4151 Show error ID if available from Raven and report react errors
  src/components/crash-message/crash-message.jsx
  src/containers/error-boundary.jsx
Labels: pr - good to merge

#4153 Make remixing/saving faster by marking all assets as clean to start.
  src/lib/vm-manager-hoc.jsx
Labels: pr - good to merge, pr - needs review

#4160 refactored font loading state to be in redux
  src/lib/font-loader-hoc.jsx
  src/lib/vm-manager-hoc.jsx
  src/reducers/fonts-loaded.js
  src/reducers/gui.js
  src/reducers/project-state.js
Labels: pr - good to merge

#4144 On modal mount, push history if current history state doesn't match this modal's id
  src/containers/modal.jsx
  test/helpers/selenium-helper.js
  test/integration/sprites.test.js
Labels: pr - good to merge

#4146 Implement list import and export from files
  package.json
  src/components/monitor/monitor.jsx
  src/containers/monitor.jsx
  src/lib/download-text.js
  src/lib/import-csv.js
  src/lib/variable-utils.js
Labels: pr - needs review

#4136 The file uploader file input should accept .sb files as well.
  package.json
  src/containers/sb-file-uploader.jsx
Labels: pr - needs review

#4172 More library updates
  src/lib/libraries/backdrops.json
  src/lib/libraries/costumes.json
  src/lib/libraries/sprites.json
Labels: pr - needs review

#4162 Add telemetry opt-in/opt-out dialog
  src/components/gui/gui.jsx
  src/components/telemetry-modal/telemetry-modal-header.png
  src/components/telemetry-modal/telemetry-modal.css
  src/components/telemetry-modal/telemetry-modal.jsx
  src/containers/gui.jsx
  src/lib/app-state-hoc.jsx
  src/playground/render-gui.jsx
  src/reducers/gui.js
  src/reducers/modals.js
Labels: pr - good to merge

#4169 translate form validation string
  src/components/menu-bar/login-dropdown.jsx
Labels: pr - good to merge

#4204 Fix #4203 by checking whether a target exists before asking whether i…
  src/lib/blocks.js
Labels: pr - good to merge

#4210 Use the loading screen in player mode
  src/components/gui/gui.jsx
  src/components/loader/loader.css
  src/components/stage-wrapper/stage-wrapper.jsx
Labels: pr - good to merge

#4208 Change WebGL link
  src/components/webgl-modal/webgl-modal.jsx
Labels: pr - needs review
