Repository scratchfoundation/scratch-gui, pull requests merged in 2018-09, with the labels that each got.

#3061 Deploy smoke branch
  package.json
  src/components/crash-message/crash-message.jsx
  src/containers/paint-editor-wrapper.jsx
Labels: pr - needs review

#3078 chore(package): update react-tooltip to version 3.8.0
  package.json
Labels: greenkeeper, pr - good to merge

#3080 chore(package): update scratch-vm to version 0.2.0-prerelease.20180906133035
  package.json
Labels: greenkeeper, pr - needs review

#3016 make project title editable, both in standalone and www modes
  README.md
  src/components/gui/gui.jsx
  src/components/menu-bar/menu-bar.css
  src/components/menu-bar/menu-bar.jsx
  src/components/menu-bar/project-title-input.css
  src/components/menu-bar/project-title-input.jsx
  src/components/prompt/prompt.jsx
  src/containers/gui.jsx
  src/containers/project-loader.jsx
  src/containers/project-saver.jsx
  src/css/colors.css
  src/lib/project-loader-hoc.jsx
  src/lib/titled-hoc.jsx
  src/playground/player.jsx
  src/playground/render-gui.jsx
  src/reducers/gui.js
  src/reducers/project-title.js
  test/integration/blocks.test.js
  test/integration/examples.test.js
Labels: feature, pr - good to merge

#3072 Refactor for hardware extensions
  package.json
  src/components/connection-modal/auto-scanning-step.jsx
  src/components/connection-modal/connected-step.jsx
  src/components/connection-modal/connecting-step.jsx
  src/components/connection-modal/connection-modal.css
  src/components/connection-modal/connection-modal.jsx
  src/components/connection-modal/error-step.jsx
  src/components/connection-modal/peripheral-tile.jsx
  src/components/connection-modal/scanning-step.jsx
  src/containers/auto-scanning-step.jsx
  src/containers/blocks.jsx
  src/containers/connection-modal.jsx
  src/containers/scanning-step.jsx
  src/lib/libraries/extensions/index.jsx
  src/lib/libraries/extensions/peripheral-connection/ev3/ev3-hub-illustration.svg
  src/lib/libraries/extensions/peripheral-connection/ev3/ev3-small.svg
  src/lib/libraries/extensions/peripheral-connection/microbit/microbit-illustration.svg
  src/lib/libraries/extensions/peripheral-connection/microbit/microbit-small.svg
  src/lib/libraries/extensions/peripheral-connection/wedo/wedo-button-illustration.svg
  src/lib/libraries/extensions/peripheral-connection/wedo/wedo-illustration.svg
  src/lib/libraries/extensions/peripheral-connection/wedo/wedo-small.svg
Labels: pr - good to merge

#3109 Remove branding from translate extension
  src/lib/libraries/extensions/index.jsx
  src/lib/libraries/extensions/translate.png
Labels: pr - good to merge

#3038 Use SVG for ask/wait prompt
  src/components/question/icon--enter.svg
  src/components/question/question.css
  src/components/question/question.jsx
Labels: pr - good to merge

#3117 chore(package): update postcss-simple-vars to version 5.0.1
  package.json
Labels: greenkeeper

#3118 chore(package): update scratch-paint to version 0.2.0-prerelease.2018…
  package.json
Labels: greenkeeper

#3106 Make title field shrink for smaller screens
  src/components/menu-bar/menu-bar.css
  src/components/menu-bar/menu-bar.jsx
  src/components/menu-bar/project-title-input.css
  src/components/menu-bar/project-title-input.jsx
Labels: pr - good to merge

#3099 Attempt to get monitor labels from VM
  package.json
  src/containers/monitor.jsx
  src/lib/monitor-adapter.js
Labels: pr - needs review

#3134 Update paint in smoke
  package.json
Labels: pr - needs review

#3137 Restyle the question answer box for RTL
  src/components/question/question.css
Labels: localization, pr - good to merge

#3146 Update paint to version that fixes crash when drawing transparent shapes in bitmap
  package.json
Labels: pr - good to merge

#3148 Deploy to master
  README.md
  package.json
  src/components/browser-modal/browser-modal.jsx
  src/components/connection-modal/auto-scanning-step.jsx
  src/components/connection-modal/connected-step.jsx
  src/components/connection-modal/connecting-step.jsx
  src/components/connection-modal/connection-modal.css
  src/components/connection-modal/connection-modal.jsx
  src/components/connection-modal/error-step.jsx
  src/components/connection-modal/peripheral-tile.jsx
  src/components/connection-modal/scanning-step.jsx
  src/components/gui/gui.jsx
  src/components/menu-bar/menu-bar.css
  src/components/menu-bar/menu-bar.jsx
  src/components/menu-bar/project-title-input.css
  src/components/menu-bar/project-title-input.jsx
  src/components/prompt/prompt.jsx
  src/components/question/icon--enter.svg
  src/components/question/question.css
  src/components/question/question.jsx
  src/containers/auto-scanning-step.jsx
  src/containers/blocks.jsx
  src/containers/connection-modal.jsx
  src/containers/gui.jsx
  src/containers/preview-modal.jsx
  src/containers/project-loader.jsx
  src/containers/project-saver.jsx
  src/containers/scanning-step.jsx
  src/css/colors.css
  src/lib/app-state-hoc.jsx
  src/lib/libraries/extensions/index.jsx
  src/lib/libraries/extensions/peripheral-connection/ev3/ev3-hub-illustration.svg
  src/lib/libraries/extensions/peripheral-connection/ev3/ev3-small.svg
  src/lib/libraries/extensions/peripheral-connection/microbit/microbit-illustration.svg
  src/lib/libraries/extensions/peripheral-connection/microbit/microbit-small.svg
  src/lib/libraries/extensions/peripheral-connection/wedo/wedo-button-illustration.svg
  src/lib/libraries/extensions/peripheral-connection/wedo/wedo-illustration.svg
  src/lib/libraries/extensions/peripheral-connection/wedo/wedo-small.svg
  src/lib/libraries/extensions/translate.png
  src/lib/project-loader-hoc.jsx
  src/lib/titled-hoc.jsx
  src/playground/index.jsx
  src/playground/player.jsx
  src/playground/render-gui.jsx
  src/reducers/gui.js
  src/reducers/project-title.js
  test/integration/blocks.test.js
  test/integration/examples.test.js
Labels: pr - needs review

#3153 [Smoke] Allow loading tutorial using query parameters in URL.
  src/lib/app-state-hoc.jsx
  src/lib/libraries/decks/index.jsx
  src/lib/tutorial-from-url.js
  src/reducers/gui.js
Labels: needs-qa, pr - good to merge

#3170 Increase timeout in integration test for loading project with url
  test/integration/project-loading.test.js
Labels: pr - needs review

#3162 Deploy Smoke to Master
  src/lib/app-state-hoc.jsx
  src/lib/libraries/decks/index.jsx
  src/lib/tutorial-from-url.js
  src/reducers/gui.js
  test/integration/project-loading.test.js
Labels: pr - good to merge

#3145 Localize default project
  src/containers/costume-tab.jsx
  src/containers/stage-selector.jsx
  src/containers/target-pane.jsx
  src/lib/default-project/index.js
  src/lib/default-project/project-data.js
  src/lib/default-project/project.json
  src/lib/empty-assets.js
  src/lib/file-uploader.js
  src/lib/project-loader-hoc.jsx
  src/lib/shared-messages.js
  src/lib/storage.js
  test/unit/util/project-loader-hoc.test.jsx
Labels: localization, pr - good to merge

#3174 fixRepeatDecode
  src/containers/sprite-selector-item.jsx
Labels: pr - good to merge

#3169 Use new APIs for renderer and canvas
  package.json
  src/containers/stage.jsx
Labels: pr - good to merge

#3171 Remove ‘he’ from the languages to ignore
  src/components/language-selector/language-selector.jsx
Labels: localization, pr - good to merge

#3193 Remove duplicate deps
  package.json
Labels: pr - needs review

#3143 Testing a new gui component for alerts
  src/components/alerts/alert.css
  src/components/alerts/alerts.jsx
  src/components/gui/gui.css
  src/components/gui/gui.jsx
  src/containers/alerts.jsx
  src/containers/gui.jsx
  src/css/z-index.css
  src/lib/vm-listener-hoc.jsx
  src/reducers/alerts.js
  src/reducers/gui.js
Labels: pr - good to merge

#3164 Localize library tags
  src/components/library/library.jsx
  src/components/tag-button/tag-button.jsx
  src/containers/tag-button.jsx
  src/lib/libraries/backdrop-tags.js
  src/lib/libraries/sound-tags.js
  src/lib/libraries/sprite-tags.js
  src/lib/libraries/tag-messages.js
Labels: pr - good to merge

#3070 adds support for account navigation, registration, login, delivered from www
  src/components/gui/gui.jsx
  src/components/menu-bar/account-nav.css
  src/components/menu-bar/account-nav.jsx
  src/components/menu-bar/dropdown-caret.svg
  src/components/menu-bar/login-dropdown.css
  src/components/menu-bar/login-dropdown.jsx
  src/components/menu-bar/menu-bar-menu.jsx
  src/components/menu-bar/menu-bar.css
  src/components/menu-bar/menu-bar.jsx
  src/components/menu/menu.jsx
  src/containers/account-nav.jsx
  src/containers/menu-item.jsx
  src/lib/vm-listener-hoc.jsx
  src/reducers/menus.js
Labels: feature

#3132 Set lang attribute for screen readers
  src/containers/language-selector.jsx
Labels: pr - good to merge

#3209 Show multiple alerts in a stack and allow for custom alert icons.
  package.json
  src/components/alerts/alert.css
  src/components/alerts/alert.jsx
  src/components/alerts/alerts.jsx
  src/containers/alert.jsx
  src/containers/alerts.jsx
  src/lib/vm-listener-hoc.jsx
  src/reducers/alerts.js
Labels: pr - good to merge

#3200 Expose AppStateHOC component
  src/index.js
Labels: pr - good to merge

#3205 Add an indicator to show that the microphone is listening
  src/components/mic-indicator/mic-indicator.css
  src/components/mic-indicator/mic-indicator.jsx
  src/components/mic-indicator/mic-indicator.svg
  src/components/monitor-list/monitor-list.jsx
  src/components/question/question.css
  src/components/question/question.jsx
  src/components/stage/stage.css
  src/components/stage/stage.jsx
  src/containers/stage.jsx
  src/css/z-index.css
  src/lib/screen-utils.js
  src/lib/vm-listener-hoc.jsx
  src/reducers/gui.js
  src/reducers/mic-indicator.js
Labels: pr - good to merge

#3144 log workspace update errors
  src/containers/blocks.jsx
Labels: pr - good to merge

#3239 Don't show the "Give Feedback" button if there is a session
  src/components/menu-bar/menu-bar.jsx
Labels: pr - good to merge

#3238 Add onShare prop to enable the share button
  src/components/gui/gui.jsx
  src/components/menu-bar/menu-bar.jsx
Labels: pr - good to merge

#3244 Deploy to Smoke Branch
  package.json
  src/components/alerts/alert.css
  src/components/alerts/alert.jsx
  src/components/gui/gui.css
  src/components/gui/gui.jsx
  src/components/library/library.jsx
  src/components/menu-bar/account-nav.css
  src/components/menu-bar/account-nav.jsx
  src/components/menu-bar/dropdown-caret.svg
  src/components/menu-bar/login-dropdown.css
  src/components/menu-bar/login-dropdown.jsx
  src/components/menu-bar/menu-bar-menu.jsx
  src/components/menu-bar/menu-bar.css
  src/components/menu-bar/menu-bar.jsx
  src/components/menu/menu.jsx
  src/components/mic-indicator/mic-indicator.css
  src/components/mic-indicator/mic-indicator.jsx
  src/components/mic-indicator/mic-indicator.svg
  src/components/monitor-list/monitor-list.jsx
  src/components/question/question.css
  src/components/question/question.jsx
  src/components/stage/stage.css
  src/components/stage/stage.jsx
  src/components/tag-button/tag-button.jsx
  src/containers/account-nav.jsx
  src/containers/alert.jsx
  src/containers/alerts.jsx
  src/containers/blocks.jsx
  src/containers/gui.jsx
  src/containers/language-selector.jsx
  src/containers/menu-item.jsx
  src/containers/stage.jsx
  src/containers/tag-button.jsx
  src/css/z-index.css
  src/index.js
  src/lib/libraries/backdrop-tags.js
  src/lib/libraries/sound-tags.js
  src/lib/libraries/sprite-tags.js
  src/lib/libraries/tag-messages.js
  src/lib/screen-utils.js
  src/lib/vm-listener-hoc.jsx
  src/reducers/alerts.js
  src/reducers/gui.js
  src/reducers/menus.js
  src/reducers/mic-indicator.js
Labels: pr - good to merge

#3058 Made border color of stage selector be same as other border colors
  src/components/stage-selector/stage-selector.css
Labels: pr - good to merge
