Repository scratchfoundation/scratch-gui, pull requests merged in 2018-04, with the labels that each got.

#1705 Show the costume/sound number similar to Scratch 2.
  src/components/asset-panel/selector.jsx
  src/components/sprite-selector-item/sprite-selector-item.css
  src/components/sprite-selector-item/sprite-selector-item.jsx
  test/unit/components/__snapshots__/sprite-selector-item.test.jsx.snap
  test/unit/components/sprite-selector-item.test.jsx
Labels: pr - needs review

#1717 Update design for editor tabs with icons, changing blocks to code.
  src/components/gui/gui.css
  src/components/gui/gui.jsx
  src/components/gui/icon--code.svg
  src/components/gui/icon--costumes.svg
  src/components/gui/icon--sounds.svg
  test/integration/blocks.test.js
  test/integration/localization.test.js
Labels: pr - good to merge

#1714 Make the stage thumbnail match the comps
  src/components/stage-selector/stage-selector.css
  src/components/stage-selector/stage-selector.jsx
Labels: pr - good to merge

#1718 Store sample rate/count for recorded sounds
  src/containers/record-modal.jsx
Labels: pr - good to merge

#1732 Manually fire tab change events onclick to fix touching tabs not working
  src/components/gui/gui.jsx
  src/containers/gui.jsx
Labels: pr - good to merge

#1725 Fix handleExtensionAdded when no targets present
  src/containers/blocks.jsx
Labels: pr - needs review

#1727 Remove toString call in the project-loader.
  src/lib/project-loader-hoc.jsx
Labels: pr - needs review

#1745 Phase 1 - Audit/Update GUI Colors
  src/components/action-menu/action-menu.css
  src/components/asset-panel/asset-panel.css
  src/components/asset-panel/selector.css
  src/components/blocks/blocks.css
  src/components/browser-modal/browser-modal.css
  src/components/close-button/close-button.css
  src/components/coming-soon/coming-soon.css
  src/components/context-menu/context-menu.css
  src/components/custom-procedures/custom-procedures.css
  src/components/feedback-form/feedback-form.css
  src/components/filter/filter.css
  src/components/forms/input.css
  src/components/forms/label.css
  src/components/green-flag/green-flag.css
  src/components/gui/gui.css
  src/components/import-modal/import-modal.css
  src/components/language-selector/language-selector.css
  src/components/library-item/library-item.css
  src/components/library/library.css
  src/components/loupe/loupe.css
  src/components/menu-bar/menu-bar.css
  src/components/meter/meter.jsx
  src/components/modal/modal.css
  src/components/monitor/monitor.css
  src/components/preview-modal/preview-modal.css
  src/components/prompt/prompt.css
  src/components/question/question.css
  src/components/record-modal/record-modal.css
  src/components/sound-editor/sound-editor.css
  src/components/sprite-info/sprite-info.css
  src/components/sprite-selector-item/sprite-selector-item.css
  src/components/sprite-selector/sprite-selector.css
  src/components/stage-header/stage-header.css
  src/components/stage-selector/stage-selector.css
  src/components/stage/stage.css
  src/components/webgl-modal/webgl-modal.css
  src/css/colors.css
Labels: pr - needs review

#1750 Fixes for load button issues.
  src/containers/load-button.jsx
Labels: pr - good to merge

#1751 Remove camera upload options from sprite and backdrop selectors.
  src/components/sprite-selector/sprite-selector.jsx
  src/components/stage-selector/stage-selector.jsx
Labels: pr - needs review

#1754 Add costume size/sound length details to sprite tile and update styling
  package.json
  src/components/asset-panel/icon--sound.svg
  src/components/asset-panel/selector.css
  src/components/asset-panel/selector.jsx
  src/components/sprite-selector-item/sprite-selector-item.css
  src/components/sprite-selector-item/sprite-selector-item.jsx
  src/containers/costume-tab.jsx
  src/containers/sound-tab.jsx
  test/unit/components/__snapshots__/sprite-selector-item.test.jsx.snap
  test/unit/components/sprite-selector-item.test.jsx
Labels: pr - needs review

#1738 Update default project with new more compact serialization.
  package.json
  src/lib/default-project/project.json
Labels: pr - needs review

#1761 Add more information to error boundary messages
  src/containers/error-boundary.jsx
Labels: pr - good to merge

#1764 Add editor drag mode for popping sprites of stage.
  src/components/stage/stage.css
  src/components/stage/stage.jsx
  src/containers/stage.jsx
Labels: needs-qa, pr - good to merge

#1772 Update scratch-vm
  package.json
Labels: pr - good to merge

#1773 Add EV3 and microbit to extensions library
  src/lib/libraries/extensions/ev3.png
  src/lib/libraries/extensions/index.js
  src/lib/libraries/extensions/microbit.png
Labels: pr - good to merge

#1774 Adjust language in selectors and libraries
  src/components/sprite-selector/sprite-selector.jsx
  src/components/stage-selector/stage-selector.jsx
  src/containers/backdrop-library.jsx
  src/containers/costume-library.jsx
  src/containers/costume-tab.jsx
  src/containers/extension-library.jsx
  src/containers/sound-library.jsx
  src/containers/sound-tab.jsx
  src/containers/sprite-library.jsx
  test/integration/costumes.test.js
  test/integration/sounds.test.js
Labels: pr - needs review

#1796 Fix issue where loading a project while in costume tab yields oops page.
  src/containers/costume-tab.jsx
Labels: pr - good to merge

#1779 Upload a sound file
  src/components/action-menu/action-menu.css
  src/components/action-menu/action-menu.jsx
  src/containers/sound-tab.jsx
Labels: needs-qa, pr - good to merge

#1802 Resolve issue with costume Button 4-b
  src/lib/libraries/costumes.json
  src/lib/libraries/sprites.json
Labels: pr - good to merge

#1786 Remove feedback form
  src/components/feedback-form/feedback-form.css
  src/components/feedback-form/feedback-form.jsx
  src/components/gui/gui.jsx
  src/components/menu-bar/icon--feedback.svg
  src/components/menu-bar/menu-bar.css
  src/components/menu-bar/menu-bar.jsx
  src/containers/gui.jsx
  src/reducers/modals.js
Labels: pr - good to merge

#1787 Use unique ids for the toolbox elements that change per sprite
  src/lib/make-toolbox-xml.js
Labels: performance, pr - good to merge

#1798 Adjustments to string operator default arguments
  src/lib/make-toolbox-xml.js
  test/integration/blocks.test.js
Labels: pr - good to merge

#1800 Reorder and add default arguments to gt, lt, eq blocks
  src/lib/make-toolbox-xml.js
Labels: pr - good to merge

#1824 Libraries Phase II
  src/components/action-menu/action-menu.jsx
  src/components/button/button.css
  src/components/button/button.jsx
  src/components/close-button/close-button.jsx
  src/components/divider/divider.css
  src/components/divider/divider.jsx
  src/components/filter/filter.css
  src/components/filter/filter.jsx
  src/components/filter/icon--filter.svg
  src/components/filter/icon--x.svg
  src/components/language-selector/language-selector.jsx
  src/components/library/library.css
  src/components/library/library.jsx
  src/components/menu-bar/menu-bar.css
  src/components/menu-bar/menu-bar.jsx
  src/components/modal/modal.css
  src/components/modal/modal.jsx
  src/components/tag-button/tag-button.css
  src/components/tag-button/tag-button.jsx
  src/containers/backdrop-library.jsx
  src/containers/costume-library.jsx
  src/containers/extension-library.jsx
  src/containers/sound-library.jsx
  src/containers/sprite-library.jsx
  src/containers/tag-button.jsx
  src/css/units.css
  src/lib/assets/icon--back.svg
  src/lib/assets/placeholder.svg
  src/lib/libraries/backdrop-tags.js
  src/lib/libraries/sound-tags.js
  src/lib/libraries/sprite-tags.js
  src/lib/libraries/sprites.json
  test/helpers/selenium-helper.js
  test/integration/costumes.test.js
  test/integration/sounds.test.js
Labels: pr - good to merge

#1828 Add USE_HEADLESS=no npm run test:integration option
  test/helpers/selenium-helper.js
Labels: pr - good to merge

#1831 Library tweaks
  src/components/filter/filter.css
  src/components/library/library.css
  src/components/modal/modal.css
Labels: pr - good to merge

#1784 Limit toolbox updates to when we tell it to update
  src/containers/blocks.jsx
Labels: performance, pr - needs review

#1448 Feature/untangle redux
  .eslintignore
  .gitignore
  package.json
  src/components/browser-modal/browser-modal.jsx
  src/containers/gui.jsx
  src/containers/language-selector.jsx
  src/lib/app-state-hoc.jsx
  src/lib/project-loader-hoc.jsx
  src/playground/blocks-only.css
  src/playground/blocks-only.jsx
  src/playground/compatibility-testing.jsx
  src/playground/error-boundary-hoc.jsx
  src/playground/index.css
  src/playground/index.ejs
  src/playground/index.jsx
  src/playground/intl.js
  src/playground/player.css
  src/playground/player.jsx
  src/reducers/intl.js
  webpack.config.js
Labels: pr - needs review

#1847 Make MINDSTORMS uppercase as per feedback from LEGO
  src/lib/libraries/extensions/index.js
Labels: pr - good to merge

#1842 Account for filter bar in library grid height
  src/components/library/library.css
  src/components/library/library.jsx
Labels: pr - good to merge

#1841 Make the library filter input full height
  src/components/filter/filter.css
  src/components/library/library.css
Labels: pr - good to merge

#1855 Search name and tags while filtering
  src/components/library/library.jsx
Labels: pr - good to merge

#1856 [Master] Account for filter bar in library grid height
  src/components/library/library.css
  src/components/library/library.jsx
Labels: pr - good to merge

#1857 [Master] Make the library filter input full height
  src/components/filter/filter.css
  src/components/library/library.css
Labels: pr - good to merge

#1861 Update scratch-vm
  package.json
Labels: pr - good to merge

#1862 Revert "Update scratch-vm"
  package.json
Labels: pr - good to merge

#1858 Allow the back button to work with libraries
  src/components/library/library.jsx
  src/containers/backdrop-library.jsx
  src/containers/costume-library.jsx
  src/containers/extension-library.jsx
  src/containers/modal.jsx
  src/containers/sound-library.jsx
  src/containers/sprite-library.jsx
Labels: pr - needs review

#1836 Upload Costumes and Backdrops (vector and bitmap)
  package.json
  src/components/stage-selector/stage-selector.jsx
  src/components/target-pane/target-pane.jsx
  src/containers/costume-tab.jsx
  src/containers/sound-tab.jsx
  src/containers/stage-selector.jsx
  src/lib/file-uploader.js
Labels: needs-qa, pr - good to merge

#1860 Update travis to publish dist and build
  .npmignore
  .travis.yml
  webpack.config.js
Labels: pr - good to merge

#1864 Updates to preview modal for release
  src/components/gui/gui.jsx
  src/components/import-modal/import-modal.css
  src/components/import-modal/import-modal.jsx
  src/components/preview-modal/preview-modal.css
  src/components/preview-modal/preview-modal.jsx
  src/containers/gui.jsx
  src/containers/import-modal.jsx
  src/containers/preview-modal.jsx
  src/reducers/modals.js
  test/integration/project-loading.test.js
Labels: pr - good to merge

#1899 Allow more mime types to be processed.
  src/lib/file-uploader.js
Labels: pr - needs review

#1883 Prevent category menu jump on sprite switch
  src/containers/blocks.jsx
Labels: pr - good to merge

#1904 Use special method for downloading blobs in Edge
  src/containers/project-saver.jsx
Labels: pr - needs review

#1911 Make sound editor buttons unselectable
  src/components/sound-editor/sound-editor.css
Labels: pr - good to merge

#1916 Revert "Bring back "Updates to preview modal for release""
  src/components/gui/gui.jsx
  src/components/import-modal/import-modal.css
  src/components/import-modal/import-modal.jsx
  src/components/preview-modal/preview-modal.css
  src/components/preview-modal/preview-modal.jsx
  src/containers/gui.jsx
  src/containers/import-modal.jsx
  src/containers/preview-modal.jsx
  src/reducers/modals.js
  test/integration/project-loading.test.js
Labels: pr - good to merge

#1915 Protect against showing costume tab for target that does not exist.
  src/lib/vm-listener-hoc.jsx
  src/reducers/targets.js
Labels: pr - good to merge

#1880 Refactor Video IO
  package.json
  src/containers/stage.jsx
  src/lib/video/camera.js
  src/lib/video/modal-video-manager.js
  src/lib/video/video-provider.js
Labels: pr - good to merge

#1918 Show "Backdrops" instead of "Costumes" in tab text if stage is selected.
  src/components/gui/gui.jsx
  src/containers/gui.jsx
Labels: pr - needs review
