Repository scratchfoundation/scratch-gui, pull requests merged in 2018-05, with the labels that each got.

#1909 Player mode
  src/components/green-flag/green-flag.css
  src/components/gui/gui.css
  src/components/gui/gui.jsx
  src/components/sprite-info/sprite-info.css
  src/components/stage-header/stage-header.css
  src/components/stage-header/stage-header.jsx
  src/components/stage-wrapper/stage-wrapper.css
  src/components/stage-wrapper/stage-wrapper.jsx
  src/components/stop-all/stop-all.css
  src/containers/stage-header.jsx
  src/containers/stage-wrapper.jsx
  src/containers/stage.jsx
  src/lib/app-state-hoc.jsx
  src/lib/storage.js
  src/playground/player.css
  src/playground/player.jsx
  src/reducers/gui.js
  src/reducers/mode.js
  src/reducers/stage-size.js
Labels: needs-qa, pr - needs review

#1924 Upload a costume from camera
  src/components/camera-modal/camera-modal.css
  src/components/camera-modal/camera-modal.jsx
  src/components/camera-modal/icon--back.svg
  src/containers/camera-modal.jsx
  src/containers/costume-tab.jsx
  src/lib/file-uploader.js
  src/reducers/modals.js
Labels: pr - needs review

#1921 Update libraries with new version of libgen
  src/lib/libraries/backdrops.json
  src/lib/libraries/costumes.json
  src/lib/libraries/sounds.json
  src/lib/libraries/sprites.json
Labels: pr - good to merge

#1932 Fix errors when dragging in player mode
  src/containers/stage.jsx
Labels: pr - good to merge

#1934 Revert localization of crash message.
  src/components/crash-message/crash-message.jsx
Labels: pr - good to merge, pr - needs review

#1935 Add sprites, costumes, and backdrops from Ipzy
  src/lib/libraries/backdrops.json
  src/lib/libraries/costumes.json
  src/lib/libraries/sprites.json
Labels: pr - good to merge

#1866 Bitmap import and export
  package.json
  src/containers/costume-tab.jsx
  src/containers/paint-editor-wrapper.jsx
Labels: pr - needs review

#1942 Make remaining text translatable, and prevent future regressions
  src/.eslintrc.js
  src/components/browser-modal/browser-modal.jsx
  src/components/crash-message/crash-message.jsx
  src/components/menu-bar/menu-bar.jsx
  src/components/prompt/prompt.jsx
  src/components/question/question.jsx
  src/components/record-modal/playback-step.jsx
  src/components/stage-selector/stage-selector.jsx
  test/helpers/selenium-helper.js
Labels: pr - good to merge

#1950 Move analytics things to environment vars
  src/lib/analytics.js
  src/playground/index.ejs
  webpack.config.js
Labels: pr - good to merge

#1956 Fix stage naming by using intl.formatMessage instead of component.
  src/components/sprite-info/sprite-info.jsx
Labels: pr - good to merge

#1953 Make error catching and reporting better
  src/containers/blocks.jsx
  src/containers/costume-tab.jsx
  src/containers/error-boundary.jsx
  src/containers/preview-modal.jsx
  src/containers/sound-tab.jsx
  src/lib/app-state-hoc.jsx
  src/lib/error-boundary-hoc.jsx
  src/lib/supported-browser.js
Labels: pr - needs review

#1957 Add an integration test for bitmap vector conversion
  test/integration/costumes.test.js
Labels: pr - needs review

#1970 Implement when backdrop switches to menu.
  src/lib/blocks.js
Labels: pr - good to merge

#1973 Limit toolbox updates
  src/containers/blocks.jsx
Labels: pr - good to merge

#1985 Bump scratch-blocks version
  package.json
Labels: pr - good to merge

#1967 Sprite upload
  package.json
  src/components/sprite-selector/sprite-selector.jsx
  src/components/target-pane/target-pane.jsx
  src/containers/sprite-library.jsx
  src/containers/target-pane.jsx
  src/lib/file-uploader.js
Labels: pr - needs review

#1993 Large readout mode for monitors
  src/components/context-menu/context-menu.css
  src/components/monitor-list/monitor-list.jsx
  src/components/monitor/default-monitor.jsx
  src/components/monitor/large-monitor.jsx
  src/components/monitor/monitor.css
  src/components/monitor/monitor.jsx
  src/containers/monitor.jsx
Labels: pr - needs review

#1996 Add several new integration tests to the GUI
  test/integration/blocks.test.js
  test/integration/costumes.test.js
  test/integration/sounds.test.js
  test/integration/sprites.test.js
Labels: pr - needs work

#2000 Update to webpack 4
  package.json
  webpack.config.js
Labels: pr - good to merge

#2005 Optimize the logo SVG
  src/components/menu-bar/scratch-logo.svg
Labels: pr - good to merge

#1999 Replace babel-preset-es2015 with babel-preset-env
  .babelrc
  package.json
Labels: pr - good to merge

#2001 Replace buffer-loader with arraybuffer-loader
  package.json
  src/lib/default-project/index.js
Labels: pr - good to merge

#1989 Add random backdrop menu option
  src/lib/blocks.js
Labels: pr - needs review

#2010 Add setAppElement to GUI
  src/components/modal/modal.css
  src/containers/gui.jsx
  src/playground/index.jsx
Labels: pr - good to merge

#2011 Consume monitor mode and position from VM
  src/components/monitor-list/monitor-list.jsx
  src/components/monitor/monitor.css
  src/components/monitor/monitor.jsx
  src/containers/monitor.jsx
Labels: pr - good to merge

#2035 Update scratch-vm dependency
  package.json
Labels: pr - good to merge

#2019 Make slider and list monitors update variables in the VM
  package.json
  src/components/monitor-list/monitor-list.jsx
  src/components/monitor/list-monitor-scroller.jsx
  src/components/monitor/list-monitor.jsx
  src/components/monitor/monitor.css
  src/components/monitor/monitor.jsx
  src/components/monitor/slider-monitor.jsx
  src/containers/list-monitor.jsx
  src/containers/monitor-list.jsx
  src/containers/monitor.jsx
  src/containers/slider-monitor.jsx
  src/lib/variable-utils.js
Labels: pr - needs review

#2046 remove question event listener on stage unmount
  src/containers/stage.jsx
Labels: pr - good to merge

#2015 Add instructions to PR template browser coverage section
  .github/PULL_REQUEST_TEMPLATE.md
Labels: pr - good to merge

#2041 Interact with blocks categories by id instead of by name
  package.json
  src/containers/blocks.jsx
  src/containers/extension-library.jsx
  src/lib/libraries/extensions/index.js
  src/lib/make-toolbox-xml.js
Labels: pr - good to merge

#2020 Project loader refactor
  src/components/stage-wrapper/stage-wrapper.css
  src/lib/hash-parser-hoc.jsx
  src/lib/project-loader-hoc.jsx
  src/playground/blocks-only.jsx
  src/playground/compatibility-testing.jsx
  src/playground/index.jsx
  src/playground/player.jsx
  test/unit/util/hash-project-loader-hoc.test.jsx
  test/unit/util/project-loader-hoc.test.jsx
Labels: pr - good to merge

#2075 Replace white rectangle bitmap with empty svg for default backdrop
  src/lib/default-project/project.json
Labels: pr - needs review

#2077 Don’t load null project id
  src/lib/project-loader-hoc.jsx
Labels: pr - good to merge

#2082 Fix monitor scaling, positioning and draggability in fullscreen mode
  src/components/monitor-list/monitor-list.css
  src/components/monitor-list/monitor-list.jsx
  src/components/monitor/list-monitor-scroller.jsx
  src/components/monitor/list-monitor.jsx
  src/components/monitor/monitor.css
  src/components/monitor/monitor.jsx
  src/components/stage/stage.jsx
  src/containers/monitor.jsx
  src/containers/stage.jsx
Labels: pr - good to merge

#1987 Publish develop builds to NPM
  .travis.yml
Labels: pr - good to merge

#2103 Update scratch-paint to hide font dropdown
  package.json
Labels: pr - good to merge

#2104 Smoke test branch -> Develop
  package.json
Labels: pr - good to merge

#2102 Fix several minor monitor issues from recent testing
  src/components/monitor-list/monitor-list.jsx
  src/components/monitor/monitor.css
  src/components/monitor/slider-monitor.jsx
Labels: pr - good to merge

#2115 Hide block inputs when entering fullscreen mode
  src/containers/blocks.jsx
Labels: pr - needs review

#2083 Feature/refactor gui store
  src/components/gui/gui.jsx
  src/components/menu-bar/menu-bar.jsx
  src/containers/blocks.jsx
  src/containers/cards.jsx
  src/containers/costume-tab.jsx
  src/containers/custom-procedures.jsx
  src/containers/gui.jsx
  src/containers/monitor-list.jsx
  src/containers/monitor.jsx
  src/containers/paint-editor-wrapper.jsx
  src/containers/project-loader.jsx
  src/containers/project-saver.jsx
  src/containers/record-modal.jsx
  src/containers/sound-editor.jsx
  src/containers/sound-tab.jsx
  src/containers/sprite-selector-item.jsx
  src/containers/stage-header.jsx
  src/containers/stage-selector.jsx
  src/containers/stage.jsx
  src/containers/target-pane.jsx
  src/containers/tips-library.jsx
  src/index.js
  src/lib/app-state-hoc.jsx
  src/lib/vm-listener-hoc.jsx
  src/playground/blocks-only.jsx
  src/playground/compatibility-testing.jsx
  src/playground/index.jsx
  src/playground/player.jsx
  src/reducers/block-drag.js
  src/reducers/cards.js
  src/reducers/color-picker.js
  src/reducers/custom-procedures.js
  src/reducers/editor-tab.js
  src/reducers/gui.js
  src/reducers/hovered-target.js
  src/reducers/menus.js
  src/reducers/modals.js
  src/reducers/mode.js
  src/reducers/monitor-layout.js
  src/reducers/monitors.js
  src/reducers/stage-size.js
  src/reducers/targets.js
  src/reducers/toolbox.js
  src/reducers/vm.js
  test/unit/containers/sound-editor.test.jsx
  test/unit/containers/sprite-selector-item.test.jsx
  webpack.config.js
Labels: pr - good to merge

#2124 Force a min viewport size to scroll around the UI instead of breaking
  src/playground/index.css
Labels: pr - good to merge

#2098 Add tags to many sprites and sounds
  src/lib/libraries/backdrops.json
  src/lib/libraries/costumes.json
  src/lib/libraries/sound-tags.js
  src/lib/libraries/sounds.json
  src/lib/libraries/sprites.json
Labels: pr - good to merge

#2140 Add sound library tags for legacy sounds
  src/lib/libraries/sounds.json
Labels: pr - good to merge

#2143 chore(package): update scratch-paint to version 0.2.0-prerelease.2018…
  package.json
Labels: pr - needs review

#2136 Make new default backdrop included in build
  src/lib/default-project/739b5e2a2435f6e1ec2993791b423146.png
  src/lib/default-project/cd21514d0531fdffb22204e0ec5ed84a.svg
  src/lib/default-project/index.js
Labels: pr - good to merge

#2133 Show a coming-soon backpack
  src/components/backpack/backpack.css
  src/components/backpack/backpack.jsx
  src/components/blocks/blocks.css
  src/components/gui/gui.jsx
  src/playground/index.jsx
Labels: pr - needs review

#2141 Add 'story' letters to libraries
  src/lib/libraries/costumes.json
  src/lib/libraries/sounds.json
  src/lib/libraries/sprites.json
Labels: pr - good to merge

#2131 Show username block in sensing
  package.json
  src/lib/make-toolbox-xml.js
  src/lib/opcode-labels.js
Labels: pr - needs review

#2146 Fix toolbox refreshing for new variables after switching tabs
  src/containers/blocks.jsx
Labels: pr - good to merge

#2145 Move error boundary out beyond the project loader
  src/containers/gui.jsx
Labels: pr - good to merge

#1991 Replace platform with bowser for browser detection
  package.json
  src/containers/error-boundary.jsx
  src/lib/audio/shared-audio-context.js
  src/lib/supported-browser.js
Labels: pr - good to merge

#2138 Force the tooltips to close to fix touch devices
  src/components/action-menu/action-menu.jsx
Labels: pr - needs review

#2150 Update scratch-vm and scratch-render
  package.json
Labels: pr - needs review

#2168 Change list monitor styles
  src/components/monitor/monitor.css
Labels: pr - needs review

#2151 Share blocks to the stage
  src/components/sprite-selector/sprite-selector.css
  src/components/stage-selector/stage-selector.css
  src/components/stage-selector/stage-selector.jsx
  src/containers/stage-selector.jsx
Labels: pr - good to merge

#2170 Change styles of action menu button
  src/components/action-menu/action-menu.css
Labels: pr - good to merge

#2184 Disable sounds in scratch-blocks
  src/containers/blocks.jsx
Labels: pr - good to merge

#2169 Reset scroll position when clicking library category button
  src/components/library/library.jsx
Labels: pr - needs review

#2192 Add translation extension
  src/lib/libraries/extensions/index.js
  src/lib/libraries/extensions/translate.png
Labels: pr - good to merge

#2175 Toggle backpack when backpack host param is available
  src/components/asset-panel/asset-panel.css
  src/components/backpack/backpack.css
  src/components/backpack/backpack.jsx
  src/components/gui/gui.css
  src/components/gui/gui.jsx
  src/containers/backpack.jsx
  src/playground/index.jsx
  test/integration/backpack.test.js
Labels: pr - good to merge

#2193 update scratch-vm
  package.json
Labels: pr - good to merge

#2196 Update scratch vm, render, audio and blocks
  package.json
Labels: pr - needs review

#2164 Block Vivaldi
  src/components/browser-modal/browser-modal.jsx
  src/lib/supported-browser.js
Labels: pr - needs review

#2012 Build scratch-* dependencies with babel-loader
  webpack.config.js
Labels: pr - good to merge

#2201 CSS updates for rendering block comments and update VM.
  package.json
  src/components/blocks/blocks.css
Labels: pr - needs review
