Repository scratchfoundation/scratch-gui, pull requests merged in 2018-03, with the labels that each got.

#1558 Cache Renderer.isSupported because it takes 30ms every time and breaks if called too often
  src/components/gui/gui.jsx
Labels: pr - good to merge

#1551 Allow http url in import modal
  src/containers/import-modal.jsx
Labels: pr - needs review

#1546 Switch to the correct costume number when switching sprites
  src/containers/costume-tab.jsx
  src/containers/sound-tab.jsx
Labels: pr - needs review

#1547 Move backdrop library back to costumes tab
  src/components/stage-selector/stage-selector.jsx
  src/components/target-pane/target-pane.jsx
  src/containers/backdrop-library.jsx
  src/containers/costume-tab.jsx
  src/containers/stage-selector.jsx
  src/containers/target-pane.jsx
Labels: pr - good to merge

#1511 Minor fixes to sprite library
  src/lib/libraries/costumes.json
  src/lib/libraries/sounds.json
  src/lib/libraries/sprites.json
Labels: pr - good to merge

#1585 Try using headless chrome for integration tests
  .travis.yml
  test/helpers/selenium-helper.js
Labels: pr - needs review

#1532 Always report mouse-up to VM and send flag indicating end of drag
  src/containers/stage.jsx
Labels: pr - good to merge

#1495 Update make-toolbox-xml.js
  src/lib/make-toolbox-xml.js
Labels: pr - needs work

#1564 Save and Load sb3 projects
  src/containers/load-button.jsx
  src/containers/save-button.jsx
Labels: pr - needs review

#1610 Fix reload button on error page
  src/containers/error-boundary.jsx
Labels: pr - needs review

#1384 Make sensing "key pressed" block input droppable
  src/lib/make-toolbox-xml.js
Labels: pr - needs review

#1596 Clean up some unused prop warnings
  src/containers/costume-tab.jsx
  src/containers/target-pane.jsx
  src/lib/vm-listener-hoc.jsx
Labels: pr - good to merge

#1620 Hold scroll position on switching sprites
  src/containers/blocks.jsx
Labels: pr - good to merge

#1631 Don't prevent default on keyboard events
  src/lib/vm-listener-hoc.jsx
Labels: pr - good to merge

#1608 Fix proptype warnings for asset panel buttons
  src/components/asset-panel/selector.jsx
Labels: ergonomics, pr - needs review

#1648 Add more browsers to the unsupported list
  src/components/browser-modal/browser-modal.jsx
  src/containers/error-boundary.jsx
  src/containers/preview-modal.jsx
Labels: needs-qa, pr - good to merge

#1582 Costume tab detects added costume and switches to the current costume of the edit target
  src/containers/backdrop-library.jsx
  src/containers/costume-library.jsx
  src/containers/costume-tab.jsx
Labels: pr - needs review

#1637 Conditionally use "when stage clicked" vs "when this sprite clicked"
  src/lib/make-toolbox-xml.js
Labels: pr - needs review

#1621 Load Button Loading/Error State
  package.json
  src/components/load-button/load-button.jsx
  src/containers/gui.jsx
  src/containers/load-button.jsx
  src/containers/record-modal.jsx
  src/containers/save-button.jsx
  src/lib/default-project/project.json
  src/reducers/modals.js
Labels: pr - needs review

#1647 Make the loader message update every 5 seconds
  src/components/loader/loader.css
  src/components/loader/loader.jsx
Labels: pr - needs review

#1683 Mock-up menu bar
  src/components/button/button.css
  src/components/button/button.jsx
  src/components/language-selector/dropdown-caret.svg
  src/components/language-selector/language-icon.svg
  src/components/language-selector/language-selector.css
  src/components/language-selector/language-selector.jsx
  src/components/menu-bar/icon--mystuff.png
  src/components/menu-bar/icon--profile.png
  src/components/menu-bar/icon--see-community.svg
  src/components/menu-bar/menu-bar.css
  src/components/menu-bar/menu-bar.jsx
  src/css/colors.css
  test/unit/components/__snapshots__/button.test.jsx.snap
Labels: pr - needs review

#1682 chore(package): update scratch-blocks to version 0.1.0-prerelease.152…
  package.json
Labels: greenkeeper

#1675 Do not autofocus filter in libraries.
  src/components/filter/filter.jsx
Labels: pr - needs review

#1684 Updates the travis.yml to run the tests/build with node 8
  .travis.yml
Labels: pr - good to merge
