Repository scratchfoundation/scratch-gui, pull requests merged in 2018-08, with the labels that each got.

#2678 Hotfix: Preview to Beta changes
  src/components/browser-modal/browser-modal.jsx
  src/components/import-modal/import-modal.jsx
  src/components/menu-bar/menu-bar.jsx
  src/components/preview-modal/preview-modal.jsx
  src/components/preview-modal/welcome.png
  src/components/webgl-modal/webgl-modal.jsx
  test/smoke/browser.test.js
Labels: pr - needs review

#2761 Bring in hotfix to beta stuff to develop
  src/components/browser-modal/browser-modal.jsx
  src/components/import-modal/import-modal.jsx
  src/components/menu-bar/menu-bar.jsx
  src/components/preview-modal/preview-modal.jsx
  src/components/preview-modal/welcome.png
  src/components/webgl-modal/webgl-modal.jsx
  test/smoke/browser.test.js
Labels: pr - good to merge

#2767 Turbo mode menu
  src/components/menu-bar/menu-bar.jsx
  src/containers/controls.jsx
  src/containers/turbo-mode.jsx
  src/lib/vm-listener-hoc.jsx
  src/reducers/gui.js
  src/reducers/vm-status.js
Labels: pr - good to merge

#2764 Add direction popover with dial and rotation style changing
  src/components/direction-picker/dial.css
  src/components/direction-picker/dial.jsx
  src/components/direction-picker/direction-picker.css
  src/components/direction-picker/direction-picker.jsx
  src/components/direction-picker/icon--all-around.svg
  src/components/direction-picker/icon--dial.svg
  src/components/direction-picker/icon--dont-rotate.svg
  src/components/direction-picker/icon--handle.svg
  src/components/direction-picker/icon--left-right.svg
  src/components/sprite-info/sprite-info.jsx
  src/components/sprite-selector/sprite-selector.jsx
  src/components/target-pane/target-pane.jsx
  src/containers/direction-picker.jsx
  src/containers/target-pane.jsx
Labels: pr - needs review

#2727 Share costumes and sounds to stage
  src/components/backpack/backpack.jsx
  src/components/stage-selector/stage-selector.jsx
  src/containers/backpack.jsx
  src/containers/stage-selector.jsx
  src/lib/drop-area-hoc.jsx
Labels: pr - needs review

#2777 Instrument device connection events
  src/containers/connection-modal.jsx
Labels: pr - good to merge

#2786 Update dependencies for translations
  package.json
Labels: localization

#2760 Feature/1579 rtl
  src/components/action-menu/action-menu.css
  src/components/action-menu/action-menu.jsx
  src/components/asset-panel/selector.css
  src/components/coming-soon/coming-soon.css
  src/components/forms/label.css
  src/components/gui/gui.css
  src/components/gui/gui.jsx
  src/components/sound-editor/sound-editor.css
  src/components/sound-editor/sound-editor.jsx
  src/components/sprite-info/sprite-info.css
  src/components/sprite-info/sprite-info.jsx
  src/components/sprite-selector-item/sprite-selector-item.css
  src/components/sprite-selector/sprite-selector.css
  src/components/sprite-selector/sprite-selector.jsx
  src/components/stage-header/stage-header.css
  src/components/stage-header/stage-header.jsx
  src/components/stage-selector/stage-selector.css
  src/containers/blocks.jsx
  src/containers/gui.jsx
  src/css/z-index.css
  src/lib/rtl-locales.js
  src/reducers/locales.js
  test/unit/components/__snapshots__/sound-editor.test.jsx.snap
Labels: localization, pr - good to merge

#2580 Fix loading projects by hash on player example
  src/playground/player.jsx
  test/helpers/selenium-helper.js
  test/integration/examples.test.js
Labels: pr - good to merge

#2809 build dist, even when run without NODE_ENV=production
  webpack.config.js
Labels: ergonomics, pr - good to merge

#2799 Handle RTL for the Modal Component
  src/components/button/button.css
  src/components/camera-modal/camera-modal.css
  src/components/camera-modal/camera-modal.jsx
  src/components/connection-modal/connection-modal.css
  src/components/connection-modal/connection-modal.jsx
  src/components/connection-modal/error-step.jsx
  src/components/connection-modal/unavailable-step.jsx
  src/components/custom-procedures/custom-procedures.css
  src/components/custom-procedures/custom-procedures.jsx
  src/components/filter/filter.css
  src/components/modal/modal.css
  src/components/modal/modal.jsx
  src/components/prompt/prompt.css
  src/components/prompt/prompt.jsx
  src/components/record-modal/playback-step.jsx
  src/components/record-modal/record-modal.css
  src/components/record-modal/record-modal.jsx
  src/containers/custom-procedures.jsx
  src/containers/modal.jsx
Labels: localization, pr - good to merge

#2827 bump render and vm together
  package.json
Labels: pr - good to merge

#2834 Revert "build dist, even when run without NODE_ENV=production"
  webpack.config.js
Labels: pr - good to merge

#2772 Add device connection steps for Lego WeDo 2.0
  src/components/connection-modal/auto-scanning-step.jsx
  src/components/connection-modal/connection-modal.css
  src/components/connection-modal/connection-modal.jsx
  src/components/connection-modal/icons/searching.png
  src/components/connection-modal/scanning-step.jsx
  src/containers/auto-scanning-step.jsx
  src/containers/blocks.jsx
  src/containers/connection-modal.jsx
  src/lib/libraries/extensions/device-connection/wedo/wedo-button-illustration.svg
  src/lib/libraries/extensions/device-connection/wedo/wedo-illustration.svg
  src/lib/libraries/extensions/device-connection/wedo/wedo-small.svg
  src/lib/libraries/extensions/index.jsx
Labels: pr - good to merge

#2824 Restore deleted sprite.
  package.json
  src/components/menu-bar/menu-bar.css
  src/components/menu-bar/menu-bar.jsx
  src/containers/deletion-restorer.jsx
  src/containers/target-pane.jsx
  src/reducers/gui.js
  src/reducers/restore-deletion.js
Labels: pr - good to merge

#2831 Add hideIntro prop to GUI component
  src/components/gui/gui.jsx
  src/containers/preview-modal.jsx
Labels: pr - good to merge

#2828 Positioning custom-procedure blocks in RTL
  src/containers/custom-procedures.jsx
Labels: localization, pr - good to merge

#2835 Fix file upload regression
  src/components/action-menu/action-menu.jsx
Labels: pr - good to merge

#2845 Disable sprite restoration.
  src/components/menu-bar/menu-bar.jsx
Labels: pr - good to merge

#2806 fix for issue #2716 (brokenness in nav bar in にほんご language)
  src/components/menu-bar/menu-bar.css
Labels: pr - needs review

#2859 [Develop] Release for August 10
  package.json
  src/components/menu-bar/menu-bar.jsx
Labels: pr - good to merge

#2752 Fix tooltips for preview modal
  src/components/import-modal/import-modal.jsx
  src/components/preview-modal/preview-modal.jsx
  test/integration/backpack.test.js
  test/integration/blocks.test.js
  test/integration/costumes.test.js
  test/integration/how-tos.test.js
  test/integration/localization.test.js
  test/integration/project-loading.test.js
  test/integration/sounds.test.js
  test/integration/sprites.test.js
Labels: localization, pr - needs review

#2775 Make delete message translateable
  src/containers/sprite-selector-item.jsx
Labels: localization, pr - needs review

#2875 [Master] Update Give Feedback link
  src/components/menu-bar/menu-bar.jsx
Labels: hotfix, pr - good to merge

#2876 [Develop] Update Give Feedback link
  src/components/menu-bar/menu-bar.jsx
Labels: hotfix, pr - good to merge

#2872 Handle RTL for cards
  src/components/cards/card.css
  src/components/cards/cards.jsx
  src/containers/cards.jsx
  src/reducers/cards.js
Labels: localization, pr - good to merge

#2869 Handle RTL in menubar
  src/components/coming-soon/coming-soon.css
  src/components/menu-bar/menu-bar.css
  src/components/menu-bar/menu-bar.jsx
Labels: localization, pr - good to merge

#2885 Add project and asset host props
  src/containers/backpack.jsx
  src/containers/gui.jsx
  src/lib/backpack-api.js
  src/lib/project-loader-hoc.jsx
  src/lib/storage.js
Labels: pr - good to merge

#2890 Revert "Merge pull request #2845 from kchadha/disable-sprite-restore"
  src/components/menu-bar/menu-bar.jsx
Labels: pr - good to merge

#2864 Handle RTL in modals
  src/components/browser-modal/browser-modal.css
  src/components/browser-modal/browser-modal.jsx
  src/components/gui/gui.jsx
  src/components/import-modal/import-modal.css
  src/components/import-modal/import-modal.jsx
  src/components/preview-modal/preview-modal.css
  src/components/preview-modal/preview-modal.jsx
  src/components/webgl-modal/webgl-modal.css
  src/components/webgl-modal/webgl-modal.jsx
  src/containers/error-boundary.jsx
  src/containers/import-modal.jsx
  src/containers/preview-modal.jsx
  src/containers/webgl-modal.jsx
Labels: localization, pr - good to merge

#2897 chore(package): update scratch-blocks to version 0.1.0-prerelease.153…
  package.json
Labels: greenkeeper

#2899 Do gh-pages deploy and cleanup last
  .travis.yml
Labels: pr - good to merge

#2908 Add missing propTypes
  src/components/import-modal/import-modal.jsx
  src/containers/gui.jsx
Labels: pr - needs review

#2919 [Master] Roll back x/y rounding
  package.json
Labels: hotfix, pr - good to merge

#2920 [Develop] Roll back x/y rounding
  package.json
Labels: hotfix, pr - good to merge

#2922 chore(package): update scratch-vm to version 0.2.0-prerelease.2018082…
  package.json
Labels: pr - good to merge

#2879 Update language selection menu
  src/components/language-selector/language-selector.css
  src/components/language-selector/language-selector.jsx
  src/components/menu-bar/menu-bar.css
  src/components/menu-bar/menu-bar.jsx
  src/css/units.css
  test/integration/localization.test.js
Labels: localization, pr - good to merge

#2935 Restore the last deleted sound.
  src/components/menu-bar/menu-bar.jsx
  src/containers/sound-tab.jsx
Labels: pr - good to merge

#2950 Restore deleted costume
  src/components/menu-bar/menu-bar.jsx
  src/containers/costume-tab.jsx
Labels: pr - good to merge

#2939 added build mode 'dist' to npm build options
  README.md
  webpack.config.js
Labels: ergonomics, pr - good to merge

#2965 chore(package): update scratch-blocks to version 0.1.0-prerelease.1534979688
  package.json
Labels: pr - needs review

#2962 Fix warnings
  src/containers/controls.jsx
  src/containers/error-boundary.jsx
  src/lib/vm-listener-hoc.jsx
Labels: pr - good to merge

#2960 Remove confirmation dialog when deleting a sprite, costume, or sound.
  src/containers/sprite-selector-item.jsx
  test/integration/sounds.test.js
  test/integration/sprites.test.js
  test/unit/containers/sprite-selector-item.test.jsx
Labels: pr - needs review

#2948 Inject fonts thumbnails
  src/containers/sprite-selector-item.jsx
  test/unit/containers/sprite-selector-item.test.jsx
Labels: pr - good to merge

#2970 Pass RTL state to paint editor
  src/containers/paint-editor-wrapper.jsx
Labels: localization, pr - good to merge

#2974 Enable WeDo extension
  src/lib/libraries/extensions/index.jsx
Labels: pr - good to merge

#2980 Release August 24 to Beta
  README.md
  package.json
  src/components/asset-panel/asset-panel.css
  src/components/backpack/backpack.css
  src/components/blocks/blocks.css
  src/components/gui/gui.css
  src/components/import-modal/import-modal.jsx
  src/components/language-selector/language-selector.css
  src/components/language-selector/language-selector.jsx
  src/components/library-item/library-item.css
  src/components/menu-bar/menu-bar.css
  src/components/menu-bar/menu-bar.jsx
  src/components/prompt/prompt.css
  src/components/stage-header/stage-header.css
  src/components/target-pane/target-pane.css
  src/containers/controls.jsx
  src/containers/costume-tab.jsx
  src/containers/error-boundary.jsx
  src/containers/gui.jsx
  src/containers/paint-editor-wrapper.jsx
  src/containers/sound-tab.jsx
  src/containers/sprite-selector-item.jsx
  src/css/units.css
  src/lib/libraries/extensions/index.jsx
  src/lib/vm-listener-hoc.jsx
  test/integration/localization.test.js
  test/integration/sounds.test.js
  test/integration/sprites.test.js
  test/unit/containers/sprite-selector-item.test.jsx
  webpack.config.js
Labels: needs-qa

#3006 Update readme with tips
  README.md
Labels: pr - good to merge

#2941 Make Scratch logo a link
  src/components/menu-bar/menu-bar.jsx
Labels: needs-qa, pr - good to merge

#3021 Save now
  package.json
  src/.eslintrc.js
  src/components/menu-bar/menu-bar.css
  src/components/menu-bar/menu-bar.jsx
  src/containers/backpack.jsx
  src/containers/gui.jsx
  src/containers/project-saver.jsx
  src/lib/project-loader-hoc.jsx
  src/lib/storage.js
  src/reducers/gui.js
  src/reducers/project-id.js
  test/unit/util/project-loader-hoc.test.jsx
Labels: pr - good to merge

#3022 Mirror the speaker icon for RTL languages
  src/components/asset-panel/icon--sound-rtl.svg
  src/components/gui/gui.css
  src/components/sound-editor/sound-editor.css
  src/containers/sound-library.jsx
  src/containers/sound-tab.jsx
Labels: localization, pr - good to merge

#3020 Fix connection modal padding for RTL
  src/components/connection-modal/connection-modal.css
  src/components/modal/modal.css
Labels: pr - good to merge

#3046 Don't load the default project on top of everything
  src/lib/project-loader-hoc.jsx
  src/reducers/project-id.js
Labels: pr - good to merge

#3052 Prepare smoke branch
  README.md
Labels: pr - needs review

#3054 Zoom to fit
  package.json
  src/containers/paint-editor-wrapper.jsx
Labels: pr - good to merge
