Repository scratchfoundation/scratch-gui, pull requests merged in 2018-10, with the labels that each got.

#3255 welcome modal doesn't appear when a project is loaded directly
  src/lib/hash-parser-hoc.jsx
  test/integration/project-loading.test.js
Labels: pr - good to merge

#3272 Add dress up costumes
  src/lib/libraries/costumes.json
  src/lib/libraries/sprites.json
Labels: pr - good to merge

#3275 chore(package): update scratch-vm to version 0.2.0-prerelease.2018100…
  package.json
Labels: greenkeeper

#3257 Use defineMessages
  src/components/preview-modal/preview-modal.jsx
Labels: pr - good to merge

#3293 Fix alerts component/containers and CSS styling
  src/components/alerts/alert.css
  src/components/alerts/alert.jsx
  src/components/alerts/alerts.jsx
  src/components/close-button/close-button.css
  src/components/close-button/close-button.jsx
  src/components/close-button/icon--close-orange.svg
  src/containers/alert.jsx
  src/containers/alerts.jsx
  src/reducers/alerts.js
  test/unit/components/__snapshots__/sprite-selector-item.test.jsx.snap
Labels: pr - good to merge

#3250 Fix expensive operation in mapStateToProps
  src/containers/paint-editor-wrapper.jsx
Labels: pr - good to merge

#3298 Change Cards Close ID
  src/components/cards/cards.jsx
Labels: pr - good to merge

#3225 Fix sprite-info pane for ‘wide’ languages
  src/components/direction-picker/direction-picker.jsx
  src/components/forms/label.css
  src/components/forms/label.jsx
  src/components/sprite-info/sprite-info.css
  src/components/sprite-info/sprite-info.jsx
  src/components/sprite-selector/sprite-selector.jsx
  src/components/stage-selector/stage-selector.css
  src/containers/direction-picker.jsx
  src/lib/locale-utils.js
  src/lib/rtl-locales.js
  src/reducers/locales.js
Labels: pr - good to merge

#3305 added micIndicator prop validation
  src/components/stage/stage.jsx
  src/containers/stage.jsx
Labels: pr - needs review

#3259 Translate 2 strings on list monitor
  src/components/monitor/list-monitor-scroller.jsx
  src/components/monitor/list-monitor.jsx
Labels: pr - good to merge

#3318 chore(package): update scratch-blocks to version 0.1.0-prerelease.153…
  package.json
Labels: greenkeeper

#3337 chore(package): update scratch-paint to version 0.2.0-prerelease.2018…
  package.json
Labels: greenkeeper

#3320 Update monitor labels on the stage when language changes
  src/containers/monitor-list.jsx
  src/lib/monitor-adapter.js
  src/lib/opcode-labels.js
Labels: localization, pr - good to merge

#3303 User can load new project in 3.0
  README.md
  src/components/gui/gui.css
  src/components/gui/gui.jsx
  src/components/menu-bar/menu-bar.jsx
  src/containers/gui.jsx
  src/containers/project-saver.jsx
  src/containers/sb-file-uploader.jsx
  src/containers/sb3-downloader.jsx
  src/lib/hash-parser-hoc.jsx
  src/lib/project-fetcher-hoc.jsx
  src/lib/project-loader-hoc.jsx
  src/lib/project-saver-hoc.jsx
  src/lib/titled-hoc.jsx
  src/lib/vm-manager-hoc.jsx
  src/playground/blocks-only.jsx
  src/playground/compatibility-testing.jsx
  src/playground/player.jsx
  src/playground/render-gui.jsx
  src/reducers/gui.js
  src/reducers/project-id.js
  src/reducers/project-state.js
  src/reducers/project-title.js
  src/reducers/vm.js
  test/unit/util/hash-project-loader-hoc.test.jsx
  test/unit/util/project-fetcher-hoc.test.jsx
  test/unit/util/project-loader-hoc.test.jsx
Labels: pr - good to merge

#3309 Open sound recorder from sound block menu
  src/containers/blocks.jsx
  src/lib/blocks.js
  test/integration/blocks.test.js
Labels: pr - good to merge

#3188 Robust URL handling for tutorial and locale
  package.json
  src/lib/detect-locale.js
  src/lib/tutorial-from-url.js
  test/unit/util/detect-locale.test.js
  test/unit/util/tutorial-from-url.test.js
Labels: pr - good to merge

#3353 Get isRtl from scratch-l10n
  src/components/sprite-selector/sprite-selector.jsx
  src/lib/locale-utils.js
  src/reducers/locales.js
Labels: localization, pr - good to merge

#3354 disable onShare button
  src/components/menu-bar/menu-bar.jsx
Labels: bug, pr - good to merge

#3350 Add project loading HOC tests
  src/lib/hash-parser-hoc.jsx
  src/lib/project-fetcher-hoc.jsx
  src/lib/vm-manager-hoc.jsx
  test/unit/util/project-fetcher-hoc.test.jsx
  test/unit/util/vm-manager-hoc.test.jsx
Labels: pr - good to merge

#3306 Fix language selector alignment
  src/components/language-selector/language-selector.css
  src/components/menu-bar/menu-bar.css
Labels: pr - good to merge

#3356 Migrate Videos from YouTube
  src/components/cards/cards.jsx
  src/lib/libraries/decks/index.jsx
Labels: pr - good to merge

#3364 use can__ boolean properties to explicitly set user capabilities
  src/components/gui/gui.jsx
  src/components/menu-bar/menu-bar.jsx
  src/playground/render-gui.jsx
  test/integration/menu-bar.test.js
Labels: pr - good to merge

#3385 Sound library update
  src/lib/libraries/sounds.json
Labels: pr - good to merge

#3360 project state reducer tests, bug fixes
  README.md
  src/lib/hash-parser-hoc.jsx
  src/lib/project-fetcher-hoc.jsx
  src/lib/project-saver-hoc.jsx
  src/reducers/project-state.js
  test/unit/reducers/project-state-reducer.test.js
  test/unit/util/hash-project-loader-hoc.test.jsx
Labels: pr - good to merge

#3394 chore(package): update babel-eslint to version 10.0.1
  package.json
Labels: pr - good to merge

#3395 Update babel-loader to version 8.0.4
  .babelrc
  package.json
  webpack.config.js
Labels: pr - good to merge

#3342 Add sprite/stage watermark to the blocks workspace.
  src/components/gui/gui.css
  src/components/gui/gui.jsx
  src/components/watermark/watermark.css
  src/components/watermark/watermark.jsx
  src/containers/sprite-selector-item.jsx
  src/containers/watermark.jsx
  src/lib/get-costume-url.js
  test/unit/containers/sprite-selector-item.test.jsx
  test/unit/util/get-costume-url.test.js
Labels: pr - good to merge

#3335 Differentiate peripheral errors: request vs. disconnect
  src/containers/blocks.jsx
  src/containers/connection-modal.jsx
  src/lib/vm-listener-hoc.jsx
Labels: pr - good to merge

#3405 Update vm
  package.json
Labels: pr - needs review

#3379 sb-file-uploader gets title of any sb.* file; calls onUpdateProjectTitle
  src/components/gui/gui.jsx
  src/components/menu-bar/menu-bar.jsx
  src/containers/sb-file-uploader.jsx
  test/unit/containers/sb-file-uploader.test.jsx
Labels: pr - good to merge

#3366 Preload fonts
  src/containers/gui.jsx
  src/lib/font-loader-hoc.jsx
  src/lib/vm-manager-hoc.jsx
  test/unit/util/vm-manager-hoc.test.jsx
Labels: pr - good to merge

#3382 Add video translation
  src/components/cards/cards.jsx
  src/containers/cards.jsx
  src/lib/libraries/decks/index.jsx
  src/lib/libraries/decks/translate-video.js
  test/unit/util/translate-video.test.js
Labels: localization, pr - good to merge

#3423 Add Text to Speech extension!
  src/lib/libraries/extensions/index.jsx
  src/lib/libraries/extensions/text2speech.png
Labels: pr - good to merge

#3409 Get costume url bugfix
  src/components/gui/gui.css
  src/components/watermark/watermark.css
  src/lib/get-costume-url.js
Labels: pr - needs review

#3434 Resolves #3336: Prevent multiple peripheral alerts after language switch
  src/lib/vm-listener-hoc.jsx
Labels: pr - good to merge

#3316 Fix block direction in loading animation for RTL
  src/components/loader/loader.css
Labels: pr - needs work

#3391 handle many modes of new project creation
  src/components/menu-bar/menu-bar.jsx
  src/containers/gui.jsx
  src/containers/sb-file-uploader.jsx
  src/lib/project-fetcher-hoc.jsx
  src/lib/project-saver-hoc.jsx
  src/lib/vm-manager-hoc.jsx
  src/reducers/project-state.js
  test/unit/reducers/project-state-reducer.test.js
  test/unit/util/project-saver-hoc.test.jsx
  test/unit/util/vm-manager-hoc.test.jsx
Labels: pr - good to merge

#3437 Fix message typos
  src/lib/opcode-labels.js
Labels: localization, pr - good to merge

#3431 Refactor IntlProvider in GUI to support integration with www
  src/containers/gui.jsx
  src/lib/app-state-hoc.jsx
  src/lib/localization-hoc.jsx
  src/lib/titled-hoc.jsx
  src/reducers/project-title.js
Labels: localization, needs-qa, pr - good to merge

#3460 added showComingSoon flag prop for gui
  src/components/gui/gui.jsx
  src/components/menu-bar/menu-bar.jsx
  src/containers/gui.jsx
  src/playground/render-gui.jsx
Labels: pr - good to merge

#3467 Add a space after ‘apple’ in the join block
  src/lib/make-toolbox-xml.js
  test/integration/blocks.test.js
Labels: pr - good to merge

#3470 Fix dragging tiles
  src/components/sprite-selector-item/sprite-selector-item.jsx
  src/containers/sprite-selector-item.jsx
  test/unit/components/__snapshots__/sprite-selector-item.test.jsx.snap
Labels: pr - good to merge

#3480 chore(package): update scratch-audio to version 0.1.0-prerelease.2018…
  package.json
Labels: greenkeeper

#3490 added missing onOpenConnectionModal
  src/containers/blocks.jsx
Labels: pr - good to merge

#3436 use project state error for project state related errors
  src/containers/gui.jsx
  src/lib/project-fetcher-hoc.jsx
  src/lib/project-saver-hoc.jsx
  src/lib/vm-manager-hoc.jsx
  src/reducers/project-state.js
  test/unit/reducers/project-state-reducer.test.js
Labels: pr - good to merge

#3478 Add tutorial filters and tags, and fix translated search in libraries
  src/components/library/library.jsx
  src/containers/tips-library.jsx
  src/lib/libraries/decks/index.jsx
  src/lib/libraries/tag-messages.js
  src/lib/libraries/tutorial-tags.js
Labels: pr - good to merge

#3486 Make tutorial ids unique
  src/lib/libraries/decks/index.jsx
Labels: pr - good to merge

#3492 chore(package): update scratch-blocks to version 0.1.0-prerelease.154…
  package.json
Labels: greenkeeper

#3497 chore(package): update scratch-blocks to version 0.1.0-prerelease.154…
  package.json
Labels: greenkeeper

#3505 Add @babel/cli for generating translation strings
  package.json
Labels: pr - good to merge

#3491 Use assets stored in the vm instead of storage
  package.json
  src/components/asset-panel/selector.jsx
  src/components/sprite-selector/sprite-list.jsx
  src/components/target-pane/target-pane.jsx
  src/containers/costume-tab.jsx
  src/containers/record-modal.jsx
  src/containers/sprite-selector-item.jsx
  src/containers/stage-selector.jsx
  src/containers/watermark.jsx
  src/lib/backpack/costume-payload.js
  src/lib/backpack/sound-payload.js
  src/lib/backpack/sprite-payload.js
  src/lib/file-uploader.js
  src/lib/get-costume-url.js
  src/lib/storage.js
Labels: pr - good to merge

#3513 chore(package): update scratch-blocks to version 0.1.0-prerelease.154…
  package.json
Labels: greenkeeper

#3514 Update tutorial and close icons
  src/components/cards/card.css
  src/components/cards/cards.jsx
  src/components/cards/icon--close.svg
Labels: pr - good to merge

#3520 [Develop] Use names for tutorial URL ids
  src/lib/libraries/decks/index.jsx
  src/lib/tutorial-from-url.js
  test/unit/util/tutorial-from-url.test.js
Labels: hotfix, pr - good to merge

#3521 [Smoke] Use names for tutorial URL ids
  src/lib/libraries/decks/index.jsx
  src/lib/tutorial-from-url.js
  test/unit/util/tutorial-from-url.test.js
Labels: hotfix, pr - good to merge

#3526 [Smoke] Fix typo accessing storage in record modal
  src/containers/record-modal.jsx
Labels: hotfix, pr - good to merge

#3525 Only dispatch targetsUpdate events if the full editor is visible
  src/lib/vm-listener-hoc.jsx
Labels: pr - good to merge

#3508 shared and remix buttons
  src/components/gui/gui.jsx
  src/components/menu-bar/icon--remix.svg
  src/components/menu-bar/menu-bar.css
  src/components/menu-bar/menu-bar.jsx
Labels: pr - good to merge

#3532 Restore IntlProvider for Internet Explorer
  src/lib/app-state-hoc.jsx
Labels: critical, pr - good to merge

#3523 Hack to load a starter project for a specific tutorial
  src/containers/tips-library.jsx
  src/lib/libraries/decks/index.jsx
Labels: pr - needs review

#3565 Issue/hotfix project load
  src/reducers/project-state.js
Labels: critical, pr - good to merge

#3568 Merge hot fix from Master
  src/reducers/project-state.js
Labels: pr - good to merge

#3495 Add a hook for custom storage init
  src/containers/gui.jsx
  src/lib/storage.js
Labels: pr - good to merge

#3539 Cloud Data Provider
  package.json
  src/containers/gui.jsx
  src/lib/cloud-provider.js
  src/lib/vm-listener-hoc.jsx
  src/lib/vm-manager-hoc.jsx
Labels: pr - good to merge

#3315 Translate record modal
  src/components/record-modal/recording-step.jsx
Labels: localization, pr - good to merge

#3574 Add integration test for changing languages not clearing project
  test/integration/localization.test.js
Labels: pr - good to merge

#3535 Close quotation mark
  src/components/crash-message/crash-message.jsx
Labels: pr - good to merge

#3567 Fix CSS issues that appear when integrated with WWW
  src/components/language-selector/language-selector.css
  src/components/loader/loader.css
  src/components/loader/loader.jsx
  src/components/menu-bar/menu-bar.css
  src/components/menu/menu.css
Labels: needs discussion, pr - good to merge

#3493 send params in storage request body, so that remixing and saving as copy create links to original projects
  src/lib/project-saver-hoc.jsx
  src/reducers/project-state.js
  test/unit/util/project-saver-hoc.test.jsx
Labels: pr - good to merge

#3571 Fix custom procedure scroll issue
  src/components/custom-procedures/custom-procedures.css
  src/components/gui/gui.css
Labels: pr - good to merge

#3581 Backpack saving/using code from the workspace
  src/components/backpack/backpack.jsx
  src/components/blocks/blocks.css
  src/components/blocks/blocks.jsx
  src/containers/backpack.jsx
  src/containers/blocks.jsx
  src/lib/backpack-api.js
  src/lib/backpack/code-payload.js
  src/lib/backpack/code-thumbnail.js
  src/lib/drag-constants.js
  src/lib/drop-area-hoc.jsx
Labels: pr - good to merge
