Repository scratchfoundation/scratch-gui, pull requests merged in 2018-02, with the labels that each got.

#1432 Fix numerous draggable images in the GUI
  src/components/asset-button/asset-button.jsx
  src/components/green-flag/green-flag.jsx
  src/components/gui/gui.jsx
  src/components/icon-button/icon-button.jsx
  src/components/menu-bar/menu-bar.jsx
  src/components/record-modal/playback-step.jsx
  src/components/record-modal/recording-step.jsx
  src/components/sound-editor/sound-editor.jsx
  src/components/stage-header/stage-header.jsx
  src/components/stop-all/stop-all.jsx
  test/unit/components/__snapshots__/icon-button.test.jsx.snap
  test/unit/components/__snapshots__/sound-editor.test.jsx.snap
  test/unit/containers/__snapshots__/green-flag.test.jsx.snap
Labels: pr - good to merge

#1434 Apply a drag threshold to make clicking sprites easier
  src/containers/stage.jsx
Labels: needs-qa, pr - needs review

#1352 Detect wheel event on canvas and post data to VM
  src/containers/stage.jsx
Labels: pr - needs review

#1440 Fix issue 1212
  src/containers/blocks.jsx
Labels: pr - needs review

#1454 Remove enableExtensions prop
  src/components/gui/gui.jsx
  src/containers/gui.jsx
Labels: pr - needs review

#1455 Move active tab state into a reducer
  src/components/gui/gui.jsx
  src/containers/gui.jsx
  src/reducers/editor-tab.js
  src/reducers/gui.js
Labels: pr - needs review

#1480 Update gui to use getter for target costumes
  src/containers/costume-tab.jsx
  src/lib/blocks.js
Labels: pr - needs review

#1487 Fix deleting in sprite selector item event bubbling
  src/containers/sound-tab.jsx
  src/containers/sprite-selector-item.jsx
Labels: pr - needs review

#1508 Asset menu follow ups
  src/components/action-menu/action-menu.jsx
  src/components/asset-panel/selector.css
  src/containers/stage-selector.jsx
  src/containers/target-pane.jsx
Labels: pr - needs review

#1481 SB2 Import Modal
  src/components/close-button/close-button.css
  src/components/close-button/close-button.jsx
  src/components/close-button/icon--back.svg
  src/components/gui/gui.jsx
  src/components/import-modal/import-modal.css
  src/components/import-modal/import-modal.jsx
  src/components/preview-modal/preview-modal.css
  src/components/preview-modal/preview-modal.jsx
  src/containers/gui.jsx
  src/containers/import-modal.jsx
  src/containers/preview-modal.jsx
  src/css/colors.css
  src/reducers/modals.js
  test/integration/project-loading.test.js
Labels: pr - good to merge

#1468 Block drag
  package.json
  src/components/sprite-selector-item/sprite-selector-item.jsx
  src/components/sprite-selector/sprite-selector.css
  src/components/sprite-selector/sprite-selector.jsx
  src/components/target-pane/target-pane.jsx
  src/containers/sprite-selector-item.jsx
  src/containers/target-pane.jsx
  src/lib/vm-listener-hoc.jsx
  src/reducers/block-drag.js
  src/reducers/gui.js
  src/reducers/hovered-target.js
  test/unit/components/__snapshots__/sprite-selector-item.test.jsx.snap
  test/unit/containers/sprite-selector-item.test.jsx
Labels: pr - good to merge

#1523 Fix the GUI not updating when new project data is available
  src/containers/target-pane.jsx
  src/lib/vm-listener-hoc.jsx
Labels: pr - needs review

#1516 Nicer crash message format
  src/components/crash-message/crash-message.css
  src/components/crash-message/crash-message.jsx
  src/components/crash-message/reload.svg
  src/containers/error-boundary.jsx
Labels: pr - good to merge

#1526 Add fetching and loading states to display loading screen.
  src/components/gui/gui.jsx
  src/components/loader/bottom-block.svg
  src/components/loader/loader.css
  src/components/loader/loader.jsx
  src/components/loader/middle-block.svg
  src/components/loader/top-block.svg
  src/containers/gui.jsx
  src/lib/project-loader-hoc.jsx
Labels: pr - good to merge
