Repository scratchfoundation/scratch-gui, pull requests merged in 2018-11, with the labels that each got.

#3596 Pass onActivateBlocksTab to sprite library to switch tabs after adding.
  src/components/target-pane/target-pane.jsx
  src/containers/target-pane.jsx
  test/integration/sprites.test.js
Labels: pr - good to merge

#3594 Fix a couple areas where we are rendering too much
  src/containers/language-selector.jsx
  src/containers/sprite-selector-item.jsx
Labels: pr - good to merge

#3585 Add sprite target highlighter on sprite-tile click
  src/components/stage/stage.css
  src/components/stage/stage.jsx
  src/containers/target-highlight.jsx
  src/containers/target-pane.jsx
  src/reducers/targets.js
Labels: pr - good to merge

#3599 Initial "pictures of blocks" implementation for the backpack
  package.json
  src/containers/backpack.jsx
  src/lib/backpack/block-to-image.js
  src/lib/backpack/code-payload.js
  src/lib/backpack/code-thumbnail.js
Labels: pr - good to merge

#3583 Blur language select focus when mouse leaves
  src/components/language-selector/language-selector.jsx
  src/containers/language-selector.jsx
Labels: localization, pr - good to merge

#3603 Update to VM hotfix version
  package.json
Labels: hotfix, pr - good to merge

#3530 Add reconnect button to hardware disconnect alerts
  src/components/alerts/alert.css
  src/components/alerts/alert.jsx
  src/components/alerts/alerts.jsx
  src/components/gui/gui.css
  src/containers/alert.jsx
  src/reducers/alerts.js
Labels: pr - good to merge

#3623 Fix dropdowns on backpack items being transparent
  src/components/backpack/backpack.css
Labels: pr - good to merge

#3630 don't require onActivatedBlocksTab prop in TargetPane container
  src/containers/target-pane.jsx
Labels: pr - good to merge

#3622 Add pointer-events:none to sprite img to prevent dragging.
  src/components/sprite-selector-item/sprite-selector-item.css
Labels: pr - good to merge

#3626 Revert "Blur language select focus when mouse leaves"
  src/components/language-selector/language-selector.jsx
  src/containers/language-selector.jsx
Labels: localization, pr - good to merge

#3648 when user clickes File->New, only save if user can save
  src/components/menu-bar/menu-bar.jsx
  src/reducers/project-state.js
Labels: pr - good to merge

#3650 Fix problem with updating cloud vars to zero.
  src/lib/cloud-provider.js
  test/unit/util/cloud-provider.test.js
Labels: pr - good to merge

#3658 Use target id in volume reporter block
  package.json
  src/lib/make-toolbox-xml.js
Labels: pr - good to merge

#3655 added simple spinner component
  src/components/spinner/spinner.css
  src/components/spinner/spinner.jsx
Labels: pr - good to merge

#3635 Add basic "show more" pagination for the backpack
  src/components/backpack/backpack.css
  src/components/backpack/backpack.jsx
  src/containers/backpack.jsx
  src/lib/backpack-api.js
Labels: pr - good to merge

#3591 Fixes Close button overlap issue
  src/components/sprite-selector-item/sprite-selector-item.css
Labels: pr - needs review

#3651 removed save and save copy from beta; better menu section style handling
  src/components/menu-bar/menu-bar.jsx
  src/components/menu/menu.jsx
  src/containers/sb-file-uploader.jsx
  src/containers/sb3-downloader.jsx
  test/integration/menu-bar.test.js
Labels: pr - good to merge

#3602 define login dropdown messages, so www component will render with readable text
  src/components/menu-bar/login-dropdown.jsx
Labels: bug, pr - good to merge

#3670 Add test for Scratch Link unavailable error modal
  package.json
  test/integration/connection-modal.test.js
Labels: pr - good to merge

#3621 Strip nbsp to fix serializing svg on safari
  src/containers/backpack.jsx
  src/lib/backpack/block-to-image.js
  src/lib/backpack/jpeg-thumbnail.js
Labels: pr - good to merge

#3614 Allow code to be dragged directly to sprite tiles
  src/components/sprite-selector/sprite-list.jsx
  src/containers/stage-selector.jsx
  src/containers/target-pane.jsx
  src/lib/backpack-api.js
Labels: pr - good to merge

#3667 Add tests for uploading sprite and costume by file
  test/fixtures/100-100.svg
  test/fixtures/gh-3582-png.png
  test/integration/costumes.test.js
  test/integration/sprites.test.js
Labels: pr - good to merge

#3605 Override blocks playNote_ to emit VM event
  package.json
  src/lib/blocks.js
Labels: pr - good to merge

#3625 Layer extension button and monitors below block drag surface
  src/css/z-index.css
Labels: pr - good to merge

#3634 Fix adding extension blocks from the backpack
  src/containers/blocks.jsx
Labels: pr - good to merge

#3619 Fix backpack crashing the GUI when trying to store a cloud variable
  package.json
  src/lib/backpack/code-payload.js
  test/unit/util/code-payload.test.js
Labels: pr - good to merge

#3689 chore(package): update scratch-vm to version 0.2.0-prerelease.2018110…
  package.json
Labels: pr - good to merge

#3559 made alert type called standard alerts; used for saving, creating
  src/components/alerts/alert.css
  src/components/alerts/alert.jsx
  src/components/alerts/alerts.jsx
  src/components/close-button/close-button.jsx
  src/components/menu-bar/menu-bar.jsx
  src/components/spinner/spinner.css
  src/containers/alert.jsx
  src/css/colors.css
  src/lib/alerts/index.jsx
  src/lib/assets/icon--success.svg
  src/lib/project-saver-hoc.jsx
  src/lib/vm-listener-hoc.jsx
  src/reducers/alerts.js
  src/reducers/project-state.js
  test/unit/reducers/alerts-reducer.test.js
  test/unit/reducers/project-state-reducer.test.js
  test/unit/util/project-saver-hoc.test.jsx
Labels: pr - good to merge

#3688 Fix monitor labels for (current [v year]) block.
  src/lib/opcode-labels.js
Labels: pr - good to merge

#3696 Split up the backpack visible and backpack host options
  src/components/gui/gui.jsx
  src/playground/render-gui.jsx
Labels: pr - good to merge

#3694 Start Gui with Tutorials Library open
  src/index.js
  src/lib/app-state-hoc.jsx
  src/lib/tutorial-from-url.js
  src/reducers/gui.js
  test/integration/tutorials-shortcut.test.js
  test/unit/util/tutorial-from-url.test.js
Labels: pr - good to merge

#3731 [Master] Add HOC tracking px
  src/components/cards/cards.jsx
  src/lib/libraries/decks/index.jsx
Labels: hotfix, pr - good to merge

#3715 Extensions Library Phase 2
  src/components/library-item/bluetooth.svg
  src/components/library-item/internet-connection.svg
  src/components/library-item/library-item.css
  src/components/library-item/library-item.jsx
  src/components/library/library.jsx
  src/lib/libraries/extensions/index.jsx
  src/lib/libraries/extensions/music-small.svg
  src/lib/libraries/extensions/pen-small.svg
  src/lib/libraries/extensions/text2speech-small.svg
  src/lib/libraries/extensions/translate-small.png
  src/lib/libraries/extensions/video-sensing-small.svg
Labels: pr - good to merge

#3729 [Develop] hoc tracking px
  src/components/cards/cards.jsx
  src/lib/libraries/decks/index.jsx
Labels: hotfix, pr - good to merge

#3638 automatically save on navigating from page; hide share and community buttons while creating
  src/components/menu-bar/community-button.css
  src/components/menu-bar/community-button.jsx
  src/components/menu-bar/menu-bar.css
  src/components/menu-bar/menu-bar.jsx
  src/components/menu-bar/share-button.css
  src/components/menu-bar/share-button.jsx
  src/containers/project-watcher.jsx
  src/lib/project-saver-hoc.jsx
Labels: pr - good to merge

#3746 fixed mapDispatchToProps error
  src/containers/project-watcher.jsx
Labels: bug, pr - good to merge

#3681 added author-info, user-avatar components
  src/components/action-menu/action-menu.css
  src/components/button/button.css
  src/components/coming-soon/coming-soon.css
  src/components/gui/gui.jsx
  src/components/menu-bar/account-nav.css
  src/components/menu-bar/account-nav.jsx
  src/components/menu-bar/author-info.css
  src/components/menu-bar/author-info.jsx
  src/components/menu-bar/menu-bar.css
  src/components/menu-bar/menu-bar.jsx
  src/components/menu-bar/user-avatar.css
  src/components/menu-bar/user-avatar.jsx
  src/components/stage-header/stage-header.css
  src/css/units.css
  src/lib/titled-hoc.jsx
Labels: needs discussion, pr - good to merge

#3745 Prevent crash after deleting sprite that had been highlighted
  src/containers/target-highlight.jsx
  test/integration/stage-size.test.js
Labels: pr - good to merge

#3741 Filter for letters in the sprite/costumes libraries
  src/lib/libraries/sprite-tags.js
  src/lib/libraries/tag-messages.js
  test/integration/costumes.test.js
  test/integration/sprites.test.js
Labels: pr - good to merge

#3713 Monitor save load
  package.json
  src/components/monitor/monitor.jsx
  src/containers/list-monitor.jsx
  src/containers/monitor.jsx
  src/lib/opcode-labels.js
Labels: pr - good to merge

#3697 Fix missing fonts in backpack thumbnails
  src/lib/backpack/costume-payload.js
Labels: pr - needs review

#3724 Save 3.0 project JSON to the project server and assets to the assets server
  .gitattributes
  package.json
  src/lib/default-project/09dc888b0b7df19f70d81588ae73420e.svg
  src/lib/default-project/3696356a03a8d938318876a593572843.svg
  src/lib/project-saver-hoc.jsx
  src/lib/storage.js
  test/unit/util/project-saver-hoc.test.jsx
Labels: pr - good to merge

#3725 Handle ?tutorial= query in gui
  src/containers/gui.jsx
  src/index.js
  src/lib/app-state-hoc.jsx
Labels: pr - good to merge

#3749 Create cloud vars
  src/components/gui/gui.jsx
  src/components/prompt/prompt.css
  src/components/prompt/prompt.jsx
  src/containers/blocks.jsx
  src/containers/gui.jsx
  src/containers/prompt.jsx
  src/lib/cloud-manager-hoc.jsx
  src/lib/cloud-provider.js
  src/lib/vm-manager-hoc.jsx
  test/unit/util/cloud-manager-hoc.test.jsx
Labels: pr - needs review

#3786 Resolves #3738: Add RTL layout to new extension library.
  src/components/library-item/library-item.css
Labels: pr - needs review

#3779 saving, creation errors use alerts; alerts css improvements
  src/components/alerts/alert.css
  src/components/alerts/alert.jsx
  src/components/close-button/close-button.css
  src/lib/alerts/index.jsx
  src/lib/project-saver-hoc.jsx
  src/reducers/alerts.js
  src/reducers/project-state.js
  test/unit/reducers/project-state-reducer.test.js
Labels: pr - good to merge

#3695 Progress toward #2389 and #2390. This puts the right options in the …
  src/lib/blocks.js
Labels: pr - good to merge

#3792 Fixing library item height stretch only for extensions.
  src/components/library-item/library-item.css
  src/components/library-item/library-item.jsx
Labels: pr - good to merge

#3794 Support multiple commands from cloud data server
  src/lib/cloud-provider.js
  test/unit/util/cloud-provider.test.js
Labels: pr - good to merge

#3768 Remove the hideIntro override and default preview modal to false
  src/containers/gui.jsx
  src/lib/app-state-hoc.jsx
  src/lib/hash-parser-hoc.jsx
  src/playground/render-gui.jsx
  src/reducers/gui.js
  src/reducers/modals.js
Labels: pr - good to merge

#3780 project-watcher can request eventual callback, or immediately call ca…
  src/components/menu-bar/menu-bar.jsx
  src/containers/project-watcher.jsx
Labels: pr - good to merge

#3829 moved z-index of alerts down around modal, loader levels
  src/css/z-index.css
Labels: pr - good to merge

#3823 more font options for creator, besides only "Helvetica Neue"
  src/components/menu-bar/author-info.css
Labels: pr - good to merge

#3826 export remixProject reducer function
  src/index.js
Labels: pr - good to merge

#3798 Move URL query string handling into an HOC
  src/containers/gui.jsx
  src/lib/app-state-hoc.jsx
  src/lib/query-parser-hoc.jsx
  src/lib/tutorial-from-url.js
  src/reducers/gui.js
  test/unit/util/tutorial-from-url.test.js
Labels: pr - good to merge

#3818 Add exponential backoff for cloud provider.
  src/lib/cloud-provider.js
  test/unit/util/cloud-provider.test.js
Labels: pr - good to merge

#3776 menu bar save messaging; self-dismissing alerts
  src/components/alerts/alert.jsx
  src/components/alerts/alerts.jsx
  src/components/alerts/inline-message.css
  src/components/alerts/inline-message.jsx
  src/components/menu-bar/menu-bar.jsx
  src/components/spinner/spinner.css
  src/components/spinner/spinner.jsx
  src/containers/alert.jsx
  src/containers/alerts.jsx
  src/containers/inline-messages.jsx
  src/css/colors.css
  src/lib/alerts/index.jsx
  src/lib/project-saver-hoc.jsx
  src/reducers/alerts.js
  test/unit/reducers/alerts-reducer.test.js
  test/unit/util/project-saver-hoc.test.jsx
Labels: pr - good to merge

#3824 Fix monitor label for day of week block.
  src/lib/opcode-labels.js
  test/unit/util/opcode-labels.test.js
Labels: pr - good to merge

#3835 avoid create/save/error loops
  src/lib/alerts/index.jsx
  src/lib/project-saver-hoc.jsx
Labels: pr - good to merge

#3821 Cloud bugfixes
  src/lib/cloud-manager-hoc.jsx
  src/lib/cloud-provider.js
  test/unit/util/cloud-manager-hoc.test.jsx
  test/unit/util/cloud-provider.test.js
Labels: pr - good to merge

#3852 Add rename and delete functionality for cloud variables
  src/lib/cloud-provider.js
  test/unit/util/cloud-provider.test.js
Labels: pr - good to merge

#3850 restored close button styling; make close button appear on alert errors
  src/components/alerts/alert.css
  src/components/close-button/close-button.css
  src/lib/alerts/index.jsx
Labels: pr - good to merge

#3851 Alerts CSS width changes and hardware alerts localization
  src/components/alerts/alert.css
  src/components/alerts/alert.jsx
  src/components/alerts/alerts.jsx
  src/components/gui/gui.css
  src/containers/alert.jsx
  src/reducers/alerts.js
Labels: pr - good to merge

#3869 Do not change to backdrops tab after adding a backdrop.
  src/containers/backdrop-library.jsx
  test/integration/backdrops.test.js
  test/integration/costumes.test.js
Labels: pr - good to merge

#3872 do not attempt to autosave on gui unmounting
  src/lib/project-saver-hoc.jsx
Labels: pr - good to merge

#3882 Green flag overlay to start in player mode
  src/components/stage/stage.css
  src/components/stage/stage.jsx
  src/containers/controls.jsx
  src/containers/green-flag-overlay.jsx
  src/containers/green-flag.jsx
  src/containers/stage.jsx
  src/containers/stop-all.jsx
  src/lib/vm-listener-hoc.jsx
  src/lib/vm-manager-hoc.jsx
  src/reducers/vm-status.js
  test/unit/containers/__snapshots__/green-flag.test.jsx.snap
  test/unit/containers/green-flag.test.jsx
  test/unit/util/vm-manager-hoc.test.jsx
Labels: pr - good to merge

#3874 Stop action menu focus stealing keyboard events from the VM
  src/components/action-menu/action-menu.jsx
Labels: pr - needs review

#3885 Hide entire frame unless the VM has not started
  src/components/stage/stage.jsx
  src/containers/stage.jsx
Labels: pr - needs review

#3873 Adding RTL padding to reconnect button on alerts.
  src/components/alerts/alert.css
  src/components/alerts/alert.jsx
Labels: pr - good to merge

#3880 Prevent arrow/space from scrolling the page
  src/lib/vm-listener-hoc.jsx
Labels: pr - good to merge

#3894 [Master] Start editor with Tutorial Library open (?tutorial=all)
  src/index.js
  src/lib/app-state-hoc.jsx
  src/lib/tutorial-from-url.js
  src/reducers/gui.js
  test/integration/tutorials-shortcut.test.js
  test/unit/util/tutorial-from-url.test.js
Labels: hotfix, pr - needs review

#3859 updated scratch-l10n in package.json
  package.json
  test/integration/menu-bar.test.js
  test/integration/tutorials-shortcut.test.js
Labels: pr - good to merge

#3897 Add three awesome tutorials
  src/lib/libraries/decks/animate-char/animate-char-add-sound.gif
  src/lib/libraries/decks/animate-char/animate-char-change-color.gif
  src/lib/libraries/decks/animate-char/animate-char-jump.gif
  src/lib/libraries/decks/animate-char/animate-char-move.gif
  src/lib/libraries/decks/animate-char/animate-char-pick-another-sprite.gif
  src/lib/libraries/decks/animate-char/animate-char-pick-backdrop.gif
  src/lib/libraries/decks/animate-char/animate-char-pick-sprite.gif
  src/lib/libraries/decks/animate-char/animate-char-say-something.gif
  src/lib/libraries/decks/animate-char/animate-char-talk.gif
  src/lib/libraries/decks/animate-char/lib_Animate_a_Character.jpg
  src/lib/libraries/decks/index.jsx
  src/lib/libraries/decks/story/lib-tell-a-story.jpg
  src/lib/libraries/decks/story/story-add-background-2.gif
  src/lib/libraries/decks/story/story-conversation.gif
  src/lib/libraries/decks/story/story-flip.gif
  src/lib/libraries/decks/story/story-hide-character.gif
  src/lib/libraries/decks/story/story-pick-another-sprite.gif
  src/lib/libraries/decks/story/story-pick-backdrop.gif
  src/lib/libraries/decks/story/story-pick-sprite.gif
  src/lib/libraries/decks/story/story-say-something.gif
  src/lib/libraries/decks/story/story-show-character.gif
  src/lib/libraries/decks/story/story-switch-backdrop.gif
  src/lib/libraries/decks/videosensing/animate-char-jump.gif
  src/lib/libraries/decks/videosensing/lib_video_sensing.jpg
  src/lib/libraries/decks/videosensing/videosens-add-extension.gif
  src/lib/libraries/decks/videosensing/videosens-animate.gif
  src/lib/libraries/decks/videosensing/videosens-pet-cat.gif
  src/lib/libraries/decks/videosensing/videosens-pop.gif
Labels: pr - good to merge

#3879 Track "project changed" state in Redux
  src/containers/blocks.jsx
  src/lib/project-fetcher-hoc.jsx
  src/lib/project-saver-hoc.jsx
  src/lib/vm-listener-hoc.jsx
  src/lib/vm-manager-hoc.jsx
  src/reducers/gui.js
  src/reducers/project-changed.js
Labels: pr - good to merge

#3900 Add download and retry saving to saving error alert.
  src/components/alerts/alert.css
  src/components/alerts/alert.jsx
  src/components/alerts/alerts.jsx
  src/containers/alert.jsx
  src/lib/alerts/index.jsx
  src/lib/project-saver-hoc.jsx
  src/reducers/alerts.js
Labels: pr - good to merge

#3896 Remove color rotation while saving
  src/components/menu-bar/menu-bar.css
  src/components/menu-bar/menu-bar.jsx
Labels: pr - good to merge

#3904 Connect to cloud based on hasCloudData
  package.json
  src/lib/cloud-manager-hoc.jsx
  src/lib/cloud-provider.js
  test/unit/util/cloud-manager-hoc.test.jsx
  test/unit/util/cloud-provider.test.js
Labels: pr - good to merge

#3890 Disconnect from cloud when entering editor mode on someone else's project
  src/lib/cloud-manager-hoc.jsx
  src/reducers/gui.js
  src/reducers/mode.js
  test/unit/util/cloud-manager-hoc.test.jsx
Labels: pr - good to merge

#3905 Send snapshots from the renderer to be saved as project thumbnails
  src/lib/data-uri-to-blob.js
  src/lib/project-saver-hoc.jsx
Labels: pr - good to merge

#3907 Remove setTimeout for reattaching workspace block listener.
  src/containers/blocks.jsx
Labels: pr - needs review

#3908 Add Makey Makey extension
  src/lib/libraries/extensions/index.jsx
  src/lib/libraries/extensions/makeymakey-small.svg
  src/lib/libraries/extensions/makeymakey.png
Labels: pr - good to merge

#3891 delete existing translations before building translations, to avoid errors
  package.json
Labels: pr - good to merge

#3867 Revise alerts code to clarify and reorganize alert type handling
  src/containers/alerts.jsx
  src/containers/inline-messages.jsx
  src/reducers/alerts.js
Labels: pr - good to merge

#3820 save before saving as a copy
  src/reducers/project-state.js
  test/unit/reducers/project-state-reducer.test.js
Labels: pr - good to merge
