Repository scratchfoundation/scratch-gui, pull requests merged in 2018-06, with the labels that each got.

#2204 Update all scratch-* dependencies
  package.json
Labels: pr - good to merge

#2235 Update libraries
  src/lib/libraries/backdrops.json
  src/lib/libraries/costumes.json
  src/lib/libraries/sounds.json
  src/lib/libraries/sprites.json
Labels: pr - needs review

#2233 Add IE11 and Safari 9/10 tests to browser smoke test using Sauce
  package.json
  test/helpers/selenium-helper.js
  test/smoke/browser.test.js
Labels: pr - needs review

#2253 Run smoke test if pull request against master
  .travis.yml
Labels: pr - good to merge

#2261 Better project loading analytics and errors
  src/containers/gui.jsx
  src/containers/project-loader.jsx
  src/lib/project-loader-hoc.jsx
Labels: pr - good to merge

#2269 Npm preview channel
  .travis.yml
Labels: pr - good to merge

#2265 Add when touching hat
  package.json
  src/lib/blocks.js
  src/lib/make-toolbox-xml.js
Labels: pr - good to merge

#2294 Revert "Add when touching hat"
  src/lib/blocks.js
  src/lib/make-toolbox-xml.js
Labels: pr - good to merge

#2302 Merge smoke changes for 6/8/18 iteration to back into develop
  src/lib/blocks.js
  src/lib/make-toolbox-xml.js
Labels: QA-OK

#2305 Fix sprite selector scroll bar
  src/components/gui/gui.css
  src/components/sprite-selector/sprite-selector.css
Labels: pr - needs review

#2303 Fix "Opening the backdrop library causes the stage backdrop editor to become selected"
  src/components/action-menu/action-menu.jsx
  src/components/gui/gui.jsx
  src/containers/backdrop-library.jsx
  src/containers/costume-tab.jsx
  src/containers/gui.jsx
  src/containers/stage-selector.jsx
Labels: pr - needs review

#2226 Move z-index values to separate file
  src/components/browser-modal/browser-modal.css
  src/components/cards/card.css
  src/components/coming-soon/coming-soon.css
  src/components/context-menu/context-menu.css
  src/components/drag-layer/drag-layer.css
  src/components/gui/gui.css
  src/components/import-modal/import-modal.css
  src/components/loader/loader.css
  src/components/menu-bar/menu-bar.css
  src/components/modal/modal.css
  src/components/monitor/monitor.css
  src/components/preview-modal/preview-modal.css
  src/components/stage-header/stage-header.css
  src/components/stage/stage.css
  src/components/webgl-modal/webgl-modal.css
  src/css/z-index.css
Labels: pr - needs work

#2239 Prevent pushing tutorial cards beyond width
  src/components/cards/card.css
Labels: pr - needs review

#2281 Stage size toggle
  package.json
  src/components/gui/gui.jsx
  src/components/sprite-info/sprite-info.jsx
  src/components/sprite-selector/sprite-selector.css
  src/components/sprite-selector/sprite-selector.jsx
  src/components/stage-header/icon--small-stage.svg
  src/components/stage-header/stage-header.css
  src/components/stage-header/stage-header.jsx
  src/components/stage-selector/stage-selector.css
  src/components/stage-wrapper/stage-wrapper.jsx
  src/components/stage/stage.jsx
  src/components/target-pane/target-pane.jsx
  src/containers/blocks.jsx
  src/containers/stage-header.jsx
  src/containers/stage-selector.jsx
  src/containers/stage-wrapper.jsx
  src/containers/stage.jsx
  src/css/z-index.css
  src/lib/layout-constants.js
  src/lib/screen-utils.js
  src/reducers/stage-size.js
  test/integration/blocks.test.js
Labels: pr - good to merge

#2331 Move context menus for monitors outside of the document flow.
  src/components/monitor/monitor.jsx
  test/integration/blocks.test.js
Labels: pr - good to merge

#2333 Prune gh-pages to match our branch list after each build
  .travis.yml
  package.json
  prune-gh-pages.sh
Labels: pr - good to merge

#2336 Only run before_deploy phase once
  .travis.yml
Labels: pr - good to merge

#2346 Enable comments
  src/containers/blocks.jsx
Labels: pr - good to merge

#2323 Make costumes, sounds and sprites sortable
  src/components/asset-panel/selector.css
  src/components/asset-panel/selector.jsx
  src/components/asset-panel/sortable-asset.jsx
  src/components/drag-layer/drag-layer.css
  src/components/sprite-selector-item/sprite-selector-item.css
  src/components/sprite-selector/sprite-list.jsx
  src/components/sprite-selector/sprite-selector.css
  src/components/sprite-selector/sprite-selector.jsx
  src/components/target-pane/target-pane.jsx
  src/containers/costume-tab.jsx
  src/containers/paint-editor-wrapper.jsx
  src/containers/sound-tab.jsx
  src/containers/sprite-selector-item.jsx
  src/containers/target-pane.jsx
  src/lib/drag-constants.js
  src/lib/drag-utils.js
  src/lib/sortable-hoc.jsx
  test/unit/util/drag-utils.test.js
Labels: pr - needs work

#2326 Enable language selection menu
  src/components/language-selector/language-selector.css
  src/components/language-selector/language-selector.jsx
  src/components/menu-bar/menu-bar.css
  src/components/menu-bar/menu-bar.jsx
  src/containers/language-selector.jsx
  src/reducers/menus.js
Labels: localization, pr - good to merge

#2317 use new SoundPlayer in SoundLibrary
  package.json
  src/containers/sound-library.jsx
Labels: pr - needs review

#2365 Disable comments
  src/containers/blocks.jsx
Labels: pr - needs review

#2379 Enable comments.
  src/containers/blocks.jsx
Labels: pr - good to merge

#2363 Force new active index and value after hitting the remove button.
  src/containers/list-monitor.jsx
Labels: pr - good to merge

#2372 Close issues automatically
  .github/PULL_REQUEST_TEMPLATE.md
Labels: pr - good to merge

#2187 Backpack load contents from server
  src/components/backpack/backpack.css
  src/components/backpack/backpack.jsx
  src/containers/backpack.jsx
  src/lib/backpack-api.js
  src/playground/index.jsx
Labels: pr - good to merge

#2380 Sharing costumes and sounds to other sprites and the stage
  src/components/asset-panel/selector.jsx
  src/components/sprite-selector-item/sprite-selector-item.css
  src/components/sprite-selector/sprite-list.jsx
  src/containers/target-pane.jsx
  src/lib/sortable-hoc.jsx
Labels: pr - good to merge

#2391 Backpack 4: adding costumes and sounds from the backpack
  src/components/backpack/backpack.css
  src/components/backpack/backpack.jsx
  src/containers/backpack.jsx
  src/containers/costume-tab.jsx
  src/containers/sound-tab.jsx
  src/containers/sprite-selector-item.jsx
  src/lib/drag-constants.js
  src/lib/sortable-hoc.jsx
Labels: pr - good to merge

#2417 Localize category names in default toolbox
  package.json
  src/lib/make-toolbox-xml.js
Labels: localization, pr - good to merge

#2418 Various fixes & additions for library assets
  src/lib/libraries/backdrops.json
  src/lib/libraries/costumes.json
  src/lib/libraries/sprites.json
Labels: pr - good to merge

#2425 Changes to language in "File" menu
  src/components/menu-bar/menu-bar.jsx
Labels: pr - good to merge

#2405 Initial version of loading or switching language.
  package.json
  src/containers/blocks.jsx
  src/containers/language-selector.jsx
  src/containers/menu.jsx
  src/index.js
  src/lib/app-state-hoc.jsx
  src/lib/connected-intl-provider.jsx
  src/lib/hash-parser-hoc.jsx
  src/playground/intl.js
  src/reducers/gui.js
  src/reducers/intl.js
  src/reducers/locales.js
  test/unit/util/hash-project-loader-hoc.test.jsx
Labels: localization, pr - good to merge

#2436 Fix 2px error in stage sizing
  src/components/stage/stage.css
Labels: pr - needs review

#2441 Fix the sprite layout by making the layout code apply to the wrapper
  src/components/sprite-selector/sprite-list.jsx
  src/components/sprite-selector/sprite-selector.css
Labels: pr - good to merge

#2416 Sprite3 Save/Load
  package.json
  src/components/asset-panel/selector.jsx
  src/components/sprite-selector-item/sprite-selector-item.jsx
  src/components/sprite-selector/sprite-list.jsx
  src/components/sprite-selector/sprite-selector.jsx
  src/components/target-pane/target-pane.jsx
  src/containers/sprite-selector-item.jsx
  src/containers/target-pane.jsx
Labels: pr - good to merge

#2454 Added automatic detection of locale from browser langauge
  src/lib/app-state-hoc.jsx
  src/lib/detect-locale.js
  test/unit/util/detect-locale.test.js
Labels: localization, pr - good to merge

#2455 Use translations from scratch-blocks to generate menus
  src/lib/blocks.js
  src/lib/make-toolbox-xml.js
Labels: localization, pr - good to merge

#2406 Hide category scrollbar for blocks for webkit/edge browsers
  src/components/blocks/blocks.css
Labels: pr - good to merge

#2464 Hack to make the renderer own the stage canvas
  src/components/gui/gui.jsx
  src/components/stage/stage.jsx
  src/containers/dom-element-renderer.jsx
  src/containers/gui.jsx
  src/containers/stage.jsx
  src/playground/player.jsx
Labels: pr - good to merge

#2419 Fix booleans not showing up in monitors
  src/containers/slider-monitor.jsx
  src/lib/monitor-adapter.js
Labels: pr - needs work

#2486 Translate monitor labels
  src/lib/opcode-labels.js
Labels: localization, pr - good to merge

#2458 Try to run in full screen on tablets
  src/containers/preview-modal.jsx
  src/lib/tablet-full-screen.js
Labels: pr - good to merge

#2503 [Develop] Don't set Content-Encoding header when deploying to S3
  .travis.yml
Labels: hotfix, pr - good to merge

#2504 [Master] Don't set Content-Encoding header when deploying to S3
  .travis.yml
Labels: hotfix, pr - good to merge

#2511 Correctly apply react style object to the dom element renderer
  package.json
  src/components/stage-wrapper/stage-wrapper.jsx
  src/components/stage/stage.jsx
  src/containers/dom-element-renderer.jsx
Labels: pr - good to merge

#2505 Localize how-tos title
  src/containers/tips-library.jsx
Labels: localization, pr - good to merge

#2506 Use react-intl to translate extensions library
  src/containers/extension-library.jsx
  src/lib/libraries/extensions/index.js
  src/lib/libraries/extensions/index.jsx
Labels: localization, pr - good to merge

#2468 ignore paint editor messages in gui
  package.json
Labels: pr - good to merge

#2517 chore(package): update eslint to version 5.0.1
  package.json
Labels: pr - good to merge
