Repository scratchfoundation/scratch-gui, pull requests merged in 2018-07, with the labels that each got.

#2560 Remove duplicate scratch-* dependencies
  package.json
Labels: pr - good to merge

#2564 Update default values for GT, LT, EQ operators to be 50
  src/lib/make-toolbox-xml.js
Labels: pr - good to merge

#2548 Local Variables
  package.json
  src/components/prompt/prompt.css
  src/components/prompt/prompt.jsx
  src/containers/blocks.jsx
  src/containers/prompt.jsx
Labels: pr - good to merge

#2555 Fix the "reverse" audio effect not working with the undo stack.
  src/lib/audio/audio-effects.js
Labels: pr - good to merge

#2576 Update translate extension library tile image
  src/lib/libraries/extensions/translate.png
Labels: pr - good to merge

#2578 Swap order of “start sound” and “play sound until done”
  src/lib/make-toolbox-xml.js
Labels: pr - good to merge

#2574 Handle localized library strings for Analytics
  src/components/library-item/library-item.jsx
  src/containers/extension-library.jsx
Labels: localization, pr - good to merge

#2579 Fix device status indicator updating issues
  package.json
  src/containers/blocks.jsx
  src/containers/connection-modal.jsx
  src/lib/blocks.js
Labels: pr - good to merge

#2588 Handle mouseUp on language select for firefox
  src/components/menu-bar/menu-bar.jsx
Labels: localization, pr - good to merge

#2584 Stop block drag surface from stopping mouse enter events
  src/components/blocks/blocks.css
Labels: pr - good to merge

#2598 Change "how-to" messages to "tutorial" and update the icon to lightbulb
  src/components/cards/cards.jsx
  src/components/cards/icon--help.svg
  src/components/menu-bar/icon--help.svg
  src/components/menu-bar/menu-bar.css
  src/components/menu-bar/menu-bar.jsx
  src/containers/tips-library.jsx
  src/lib/assets/icon--tutorials.svg
  test/integration/how-tos.test.js
Labels: pr - good to merge

#2592 Issue/2514 extension lang switch
  src/containers/blocks.jsx
Labels: localization, pr - good to merge

#2604 Update Stage Select UI
  src/components/stage-selector/stage-selector.css
  src/components/stage-selector/stage-selector.jsx
Labels: pr - good to merge

#2599 Add intl polyfill for Safari 9
  package.json
  src/playground/index.jsx
Labels: pr - good to merge

#2609 Fix micro:bit extension name and description
  src/lib/libraries/extensions/index.jsx
Labels: pr - good to merge

#2575 Use bitmapAdapter for costume upload
  package.json
  src/containers/costume-library.jsx
  src/containers/costume-tab.jsx
  src/containers/stage.jsx
  src/lib/file-uploader.js
Labels: pr - good to merge

#2605 Add a new "unavailable" step to the connection flow
  src/components/connection-modal/connection-modal.css
  src/components/connection-modal/connection-modal.jsx
  src/components/connection-modal/icons/scratch-link.png
  src/components/connection-modal/unavailable-step.jsx
  src/containers/connection-modal.jsx
Labels: pr - good to merge

#2610 Fix rename variable bug
  src/containers/blocks.jsx
Labels: pr - needs review

#2622 Updates to sprite, costume, and backdrop libraries
  src/lib/libraries/backdrops.json
  src/lib/libraries/costumes.json
  src/lib/libraries/sounds.json
  src/lib/libraries/sprites.json
Labels: pr - good to merge

#2617 Do not skip safari 9 browser test because it works now
  test/smoke/browser.test.js
Labels: pr - good to merge

#2640 Widen add-extension button to match category.
  src/components/gui/gui.css
Labels: localization, pr - good to merge

#2650 Localize custom procedure modal title
  src/components/connection-modal/error-step.jsx
  src/components/custom-procedures/custom-procedures.jsx
Labels: localization, pr - needs work

#2651 EV3/Microbit critical fixes for code freeze
  src/containers/scanning-step.jsx
Labels: pr - good to merge

#2661 Change 'video motion' to 'video sensing' and minor clean-up to extension library
  src/lib/libraries/extensions/index.jsx
Labels: pr - needs review

#2663 Don’t let Google try to auto translate the GUI
  src/playground/index.ejs
Labels: pr - good to merge

#2660 chore(package): update scratch-blocks to version 0.1.0-prerelease.153…
  package.json
Labels: greenkeeper

#2655 Enable the language menu
  src/components/menu-bar/menu-bar.jsx
  test/integration/localization.test.js
Labels: feature, localization, pr - good to merge

#2665 Updates to Tutorials Library
  src/lib/libraries/decks/animate/lib_animate-a-name.jpg
  src/lib/libraries/decks/chase-game/lib-chasegame.jpg
  src/lib/libraries/decks/game/lib-pop.jpg
  src/lib/libraries/decks/index.jsx
  src/lib/libraries/decks/intro/lib-getting-started.jpg
  src/lib/libraries/decks/make-music/lib-make-music.jpg
  src/lib/libraries/decks/spin/change-color.gif
  src/lib/libraries/decks/spin/click-control.gif
  src/lib/libraries/decks/spin/click-forever.gif
  src/lib/libraries/decks/spin/click-turn.gif
  src/lib/libraries/decks/spin/drag-forever.gif
  src/lib/libraries/decks/spin/drag-turn.gif
  src/lib/libraries/decks/spin/library-spin.gif
  src/lib/libraries/decks/spin/thumb-spin.gif
  src/lib/libraries/decks/sprite/cover-add-sprite.jpg
  src/lib/libraries/decks/videos/add-backdrop.jpg
  src/lib/libraries/decks/videos/add-effects.jpg
  src/lib/libraries/decks/videos/animate-sprite.jpg
  src/lib/libraries/decks/videos/change-size.jpg
  src/lib/libraries/decks/videos/glide-around.jpg
  src/lib/libraries/decks/videos/hide-and-show.jpg
  src/lib/libraries/decks/videos/move-arrow-keys.jpg
  src/lib/libraries/decks/videos/record-a-sound.jpg
  src/lib/libraries/decks/videos/spin.jpg
Labels: pr - needs review

#2670 Don't crash the editor when a project file fails to upload.
  src/containers/project-loader.jsx
Labels: pr - good to merge

#2675 All hail the taco wizard
  src/lib/libraries/costumes.json
  src/lib/libraries/sprites.json
Labels: pr - needs review

#2677 Prevent react recycling components causing safari render bug
  src/components/connection-modal/scanning-step.jsx
Labels: pr - good to merge

#2682 Improve search and tutorial instrumentation for preview
  src/components/library/library.jsx
  src/containers/tips-library.jsx
  src/reducers/cards.js
Labels: pr - good to merge

#2684 Update Toolbox when blocks container updates and is visible.
  src/containers/blocks.jsx
Labels: pr - good to merge

#2680 Enable EV3 and micro:bit extensions
  src/lib/libraries/extensions/index.jsx
Labels: pr - needs review

#2691 Fix project loader cleanup function. Safari does not support the use of .finally
  src/containers/project-loader.jsx
Labels: pr - good to merge

#2693 Deploy July work to Preview
  package.json
  src/components/connection-modal/connecting-step.jsx
  src/components/connection-modal/connection-modal.css
  src/components/connection-modal/connection-modal.jsx
  src/components/connection-modal/error-step.jsx
  src/components/connection-modal/icons/bluetooth.svg
  src/components/connection-modal/icons/scratch-link.png
  src/components/connection-modal/icons/scratchlink.svg
  src/components/connection-modal/scanning-step.jsx
  src/components/connection-modal/unavailable-step.jsx
  src/components/custom-procedures/custom-procedures.jsx
  src/components/gui/gui.css
  src/components/library/library.jsx
  src/components/menu-bar/menu-bar.jsx
  src/components/modal/modal.css
  src/components/modal/modal.jsx
  src/containers/blocks.jsx
  src/containers/connection-modal.jsx
  src/containers/project-loader.jsx
  src/containers/scanning-step.jsx
  src/containers/tips-library.jsx
  src/lib/assets/icon--help.svg
  src/lib/libraries/backdrops.json
  src/lib/libraries/costumes.json
  src/lib/libraries/decks/animate/lib_animate-a-name.jpg
  src/lib/libraries/decks/chase-game/lib-chasegame.jpg
  src/lib/libraries/decks/game/lib-pop.jpg
  src/lib/libraries/decks/index.jsx
  src/lib/libraries/decks/intro/lib-getting-started.jpg
  src/lib/libraries/decks/make-music/lib-make-music.jpg
  src/lib/libraries/decks/spin/change-color.gif
  src/lib/libraries/decks/spin/click-control.gif
  src/lib/libraries/decks/spin/click-forever.gif
  src/lib/libraries/decks/spin/click-turn.gif
  src/lib/libraries/decks/spin/drag-forever.gif
  src/lib/libraries/decks/spin/drag-turn.gif
  src/lib/libraries/decks/spin/library-spin.gif
  src/lib/libraries/decks/spin/thumb-spin.gif
  src/lib/libraries/decks/sprite/cover-add-sprite.jpg
  src/lib/libraries/decks/videos/add-backdrop.jpg
  src/lib/libraries/decks/videos/add-effects.jpg
  src/lib/libraries/decks/videos/animate-sprite.jpg
  src/lib/libraries/decks/videos/change-size.jpg
  src/lib/libraries/decks/videos/glide-around.jpg
  src/lib/libraries/decks/videos/hide-and-show.jpg
  src/lib/libraries/decks/videos/move-arrow-keys.jpg
  src/lib/libraries/decks/videos/record-a-sound.jpg
  src/lib/libraries/decks/videos/spin.jpg
  src/lib/libraries/extensions/index.jsx
  src/lib/libraries/sounds.json
  src/lib/libraries/sprites.json
  src/playground/index.ejs
  src/reducers/cards.js
  test/integration/localization.test.js
  test/smoke/browser.test.js
Labels: pr - needs review

#2703 Use pageview with query param for tracking search usage
  src/components/library/library.jsx
Labels: pr - good to merge

#2706 [MASTER] Temporarily exclude RTL languages from the menu
  src/components/language-selector/language-selector.jsx
Labels: hotfix, pr - good to merge

#2702 Make extension help links clickable in modal
  src/components/modal/modal.css
Labels: pr - needs review

#2657 Fix cursor in fullscreen
  src/components/monitor/list-monitor.jsx
Labels: pr - needs review

#2659 Fix shadow placeholder color
  src/components/asset-panel/selector.css
  src/components/sprite-selector/sprite-selector.css
Labels: pr - good to merge

#2707 [DEVELOP] Temporarily exclude RTL languages from the language menu
  src/components/language-selector/language-selector.jsx
Labels: hotfix, pr - needs review

#2712 Bring dragging sprites to front
  src/containers/stage.jsx
Labels: pr - good to merge

#2722 Clear the workspace undo when the workspace updates.
  src/containers/blocks.jsx
Labels: pr - needs review

#2699 Add username setting to vm listener HOC
  src/lib/vm-listener-hoc.jsx
Labels: pr - good to merge

#2730 Remove costume canvas and just display tiles using <img> tags
  src/components/costume-canvas/costume-canvas.jsx
  src/components/sprite-selector-item/sprite-selector-item.css
  src/components/sprite-selector-item/sprite-selector-item.jsx
  src/components/stage-selector/stage-selector.css
  src/components/stage-selector/stage-selector.jsx
  test/unit/components/__snapshots__/sprite-selector-item.test.jsx.snap
  test/unit/components/sprite-selector-item.test.jsx
Labels: pr - good to merge

#2732 Pad bottom of costume/sound list to allow you to reach the bottom tile
  src/components/asset-panel/selector.css
Labels: pr - good to merge

#2729 Show only 2 other tutorials in last step of each tutorial.
  src/components/cards/card.css
  src/components/cards/cards.jsx
  src/lib/libraries/decks/index.jsx
Labels: pr - good to merge

#2739 Translate Spin & Arrow How-To
  src/lib/libraries/decks/index.jsx
Labels: pr - needs review
