Repository scratchfoundation/scratch-gui, pull requests merged in 2019-04, with the labels that each got.

#4709 Keep URI correct when uploading project while signed out
  src/containers/sb-file-uploader.jsx
Labels: pr - good to merge

#4712 Register callback keys for buttons used in future extensions.
  src/containers/blocks.jsx
Labels: pr - good to merge

#4720 Add Vernier Force and Accel extension
  src/lib/libraries/extensions/gdxfor/gdxfor-illustration.svg
  src/lib/libraries/extensions/gdxfor/gdxfor-small.svg
  src/lib/libraries/extensions/gdxfor/gdxfor.png
  src/lib/libraries/extensions/index.jsx
Labels: pr - good to merge

#4690 Prevent crash on load hardware ext without assets
  src/components/connection-modal/connection-modal.jsx
  src/containers/connection-modal.jsx
Labels: pr - needs review

#4644 Load library images through storage
  package.json
  src/components/library-item/library-item.jsx
  src/components/library/library.jsx
  src/components/scratch-image/scratch-image.jsx
  src/containers/library-item.jsx
  test/integration/costumes.test.js
Labels: pr - good to merge

#4724 Changing tutorial video width to be smaller
  src/components/cards/card.css
  src/components/cards/cards.jsx
Labels: pr - good to merge

#4733 Make sure to save assets before sending them to the backpack
  src/containers/backpack.jsx
Labels: pr - good to merge

#4700 upload in current project id, rather than creating new project id
  src/components/menu-bar/menu-bar.jsx
  src/containers/sb-file-uploader.jsx
  src/lib/shared-messages.js
  src/reducers/project-state.js
  test/integration/menu-bar.test.js
  test/unit/reducers/project-state-reducer.test.js
Labels: pr - good to merge

#4710 Share, See-project-page buttons will only save if project has changed
  src/components/menu-bar/menu-bar.jsx
Labels: pr - good to merge

#4755 removed confirm prompt if you are editing someone else's project and then do file -> upload
  src/containers/sb-file-uploader.jsx
Labels: pr - good to merge

#4761 Add Boost extension assets
  src/lib/libraries/extensions/boost/boost-button-illustration.svg
  src/lib/libraries/extensions/boost/boost-illustration.svg
  src/lib/libraries/extensions/index.jsx
Labels: pr - good to merge

#4676 Move projectChanged into HOC wrapping MenuBar, to avoid unnecessary renders
  src/components/menu-bar/confirm-replace-hoc.jsx
  src/components/menu-bar/menu-bar.jsx
Labels: performance, pr - needs review

#4757 Remove unneeded feedback button in menubar
  src/components/menu-bar/icon--feedback.svg
  src/components/menu-bar/menu-bar.jsx
Labels: pr - good to merge

#4753 Allow GUI consumer to receive a function for triggering saves.
  src/lib/project-saver-hoc.jsx
  test/unit/util/project-saver-hoc.test.jsx
Labels: pr - good to merge

#4756 Fix Vernier branding (“Go Direct”)
  src/lib/libraries/extensions/index.jsx
Labels: pr - good to merge

#4717 Add troubleshooting documentation
  README.md
Labels: pr - needs review
