Repository scratchfoundation/scratch-gui, pull requests merged in 2019-01, with the labels that each got.

#4223 Bump scratch-vm
  package.json
Labels: pr - good to merge

#4232 Wrap the stage canvas so that styles are not directly applied to it, fixing bounds calculations
  .gitignore
  src/components/stage/stage.css
  src/components/stage/stage.jsx
  src/lib/screen-utils.js
Labels: critical, pr - needs review

#4196 Remove Vivaldi block
  src/components/browser-modal/browser-modal.jsx
  src/lib/supported-browser.js
Labels: pr - good to merge

#4277 Make the sprite drop area from the backpack highlight and large
  src/components/backpack/backpack.css
  src/components/blocks/blocks.css
  src/components/sprite-selector/sprite-list.jsx
  src/components/sprite-selector/sprite-selector.css
  src/components/sprite-selector/sprite-selector.jsx
  src/components/stage-selector/stage-selector.css
  src/css/colors.css
Labels: pr - needs review

#4023 Fix sound editor button spacing
  src/components/sound-editor/sound-editor.css
Labels: pr - good to merge

#4284 Save project state before storing assets instead of after.
  src/lib/project-saver-hoc.jsx
Labels: critical, pr - needs review

#4287 Check for minimum versions of recommended browsers
  src/components/browser-modal/browser-modal.jsx
  src/lib/supported-browser.js
Labels: pr - needs review

#4304 Revise how unsupported browsers are handled
  src/components/browser-modal/browser-modal.css
  src/components/browser-modal/browser-modal.jsx
  src/components/browser-modal/unsupported-browser.svg
  src/components/webgl-modal/unsupported.png
  src/components/webgl-modal/webgl-modal.css
  src/containers/error-boundary.jsx
  src/lib/supported-browser.js
Labels: pr - needs review

#4298 check for non-null flyout
  src/containers/blocks.jsx
Labels: pr - good to merge

#4312 add support for onProjectLoaded
  src/containers/gui.jsx
  src/reducers/project-state.js
Labels: pr - good to merge

#4319 resolve name conflict by renaming onProjectLoaded in project-fetcher-hoc
  src/containers/gui.jsx
  src/lib/project-fetcher-hoc.jsx
  src/reducers/project-state.js
Labels: pr - good to merge

#4314 Make whole stage clickable for green flag overlay
  src/components/stage/stage.css
  src/components/stage/stage.jsx
  src/containers/green-flag-overlay.jsx
Labels: pr - good to merge

#4322 Show loading screen in fullscreen mode
  src/components/gui/gui.jsx
  src/components/loader/loader.css
  src/components/loader/loader.jsx
  src/components/stage-wrapper/stage-wrapper.jsx
  src/containers/gui.jsx
Labels: pr - good to merge

#4315 Allow putting mp3 sounds in the backpack.
  src/lib/backpack/sound-payload.js
Labels: pr - good to merge

#4357 Clear trim handles if trim cannot be completed.
  src/containers/sound-editor.jsx
Labels: pr - needs review

#4359 Adds BorderedMenuItem and use it for delete menu
  src/components/context-menu/context-menu.css
  src/components/context-menu/context-menu.jsx
  src/components/sprite-selector-item/sprite-selector-item.jsx
Labels: pr - needs review

#4354 Fix issue where you couldn't add sprites from backpack when there are no sprites
  src/containers/costume-tab.jsx
  src/containers/sound-tab.jsx
  src/containers/target-pane.jsx
  src/lib/sortable-hoc.jsx
Labels: pr - good to merge

#4362 Improve layout/paint performance in editor while running a project
  src/components/asset-panel/selector.css
  src/components/backpack/backpack.css
  src/components/sprite-selector-item/sprite-selector-item.css
  src/components/sprite-selector-item/sprite-selector-item.jsx
  test/unit/components/__snapshots__/sprite-selector-item.test.jsx.snap
Labels: pr - good to merge

#4369 Update scratch-blocks
  package.json
Labels: pr - needs review

#4377 update scratch-blocks for languages.
  package.json
Labels: localization

#4385 Add BorderedMenuItem and use it for delete menu, with updated style
  src/components/context-menu/context-menu.css
  src/components/context-menu/context-menu.jsx
  src/components/sprite-selector-item/sprite-selector-item.jsx
Labels: needs discussion, pr - needs review

#3922 Peripheral disconnect status using new runtime/vm event
  src/containers/blocks.jsx
  src/lib/vm-listener-hoc.jsx
Labels: pr - good to merge

#4405 Update WeDo 2.0 extension name
  src/lib/libraries/extensions/index.jsx
Labels: pr - good to merge

#4383 Remove scale transition from green flag, stop and sound editor buttons
  src/components/green-flag/green-flag.css
  src/components/icon-button/icon-button.css
  src/components/stop-all/stop-all.css
  src/css/colors.css
Labels: performance, pr - good to merge

#4393 Remove transition on sprite tiles to make placeholder not flash black.
  src/components/asset-panel/selector.css
  src/components/sprite-selector-item/sprite-selector-item.css
Labels: pr - good to merge

#4396 Improve sound editor performance with longer sounds
  src/components/audio-trimmer/audio-trimmer.css
  src/components/audio-trimmer/audio-trimmer.jsx
  src/components/waveform/waveform.jsx
  test/unit/components/__snapshots__/sound-editor.test.jsx.snap
Labels: pr - good to merge

#4407 Disable target updates while sound recording
  src/lib/vm-listener-hoc.jsx
  test/unit/util/vm-listener-hoc.test.jsx
Labels: pr - good to merge

#4415 Remove the redux throttle for targets update.
  src/reducers/targets.js
Labels: pr - good to merge

#4413 Move the mask on the audio meter outside the SVG for repaint performance
  src/components/meter/meter.css
  src/components/meter/meter.jsx
Labels: performance, pr - good to merge

#4417 Throttle costume and watermark updates
  src/components/sprite-selector/sprite-list.jsx
  src/containers/sprite-selector-item.jsx
  src/containers/stage-selector.jsx
  src/containers/watermark.jsx
  src/lib/backpack/sprite-payload.js
  src/lib/throttled-property-hoc.jsx
  test/unit/util/throttled-property-hoc.test.jsx
Labels: pr - good to merge

#4099 Sprite library animations no longer update the entire library state on every costume change
  src/components/library-item/library-item.css
  src/components/library-item/library-item.jsx
  src/components/library/library.jsx
  src/containers/library-item.jsx
  src/containers/sprite-library.jsx
  test/integration/costumes.test.js
Labels: blocked, pr - needs review

#4425 Use fontInliner instead of entire SVGRenderer for showing costume tiles.
  src/lib/get-costume-url.js
Labels: performance, pr - good to merge

#4447 Move rounding into sprite info to improve performance
  src/components/sprite-info/sprite-info.jsx
  src/containers/target-pane.jsx
Labels: pr - good to merge

#4440 Avoid double toolbox update on mount and when setting language
  src/containers/blocks.jsx
Labels: performance, pr - good to merge

#4452 Menus should be over most things
  src/css/z-index.css
Labels: pr - good to merge

#4457 Update project changes test
  test/integration/project-loading.test.js
Labels: pr - good to merge

#4449 Only update the toolbox when the blocks tab is visible.
  src/containers/blocks.jsx
  src/lib/make-toolbox-xml.js
  test/integration/blocks.test.js
Labels: pr - good to merge
