Repository scratchfoundation/scratch-gui, pull requests merged in 2019-02, with the labels that each got.

#4438 Export costumes and sounds!
  src/containers/costume-tab.jsx
  src/containers/monitor.jsx
  src/containers/sound-tab.jsx
  src/lib/download-url.js
Labels: needs-qa, pr - good to merge

#4433 Control/Command+S to save
  src/components/menu-bar/menu-bar.jsx
Labels: pr - needs review

#4478 [master] Hotfix/toolbox language
  src/containers/blocks.jsx
  test/integration/localization.test.js
Labels: pr - good to merge

#4471 Export costumes without inlined fonts for now
  src/containers/costume-tab.jsx
Labels: pr - needs review

#4475 Retain showBranding mode property after SET_FULL_SCREEN action is dispatched
  src/reducers/mode.js
  test/unit/reducers/mode-reducer.test.js
Labels: pr - good to merge

#4477 Move blocks z-index up to match gui
  src/components/blocks/blocks.css
  src/css/z-index.css
Labels: pr - good to merge

#4465 Make uploaded sprites not draggable
  src/lib/file-uploader.js
Labels: pr - good to merge

#4467 Call updateToolbox after adding new blocks from the backpack.
  src/containers/blocks.jsx
Labels: pr - good to merge

#4493 Fix "See Inside" not showing variables
  src/containers/blocks.jsx
  src/playground/player.css
  src/playground/player.jsx
  test/integration/blocks.test.js
Labels: pr - good to merge

#4486 Escape special characters in toolbox xml
  src/lib/make-toolbox-xml.js
  test/integration/blocks.test.js
Labels: pr - good to merge

#4495 Wait until loader becomes stale to continue in project loader tests
  test/helpers/selenium-helper.js
  test/integration/examples.test.js
  test/integration/project-loading.test.js
Labels: pr - needs work

#4505 Use blob download instead of data-uri to enable large downloads
  src/containers/costume-tab.jsx
  src/containers/monitor.jsx
  src/containers/sb3-downloader.jsx
  src/containers/sound-tab.jsx
  src/containers/target-pane.jsx
  src/lib/download-blob.js
  src/lib/download-url.js
Labels: pr - needs work

#4499 Multiple file upload for costumes, sounds, backdrops and sprites
  src/components/action-menu/action-menu.jsx
  src/components/sprite-selector/sprite-selector.jsx
  src/components/stage-selector/stage-selector.jsx
  src/containers/costume-tab.jsx
  src/containers/sound-tab.jsx
  src/lib/file-uploader.js
  test/fixtures/movie.wav
  test/fixtures/sneaker.wav
  test/integration/backdrops.test.js
  test/integration/costumes.test.js
  test/integration/sounds.test.js
  test/integration/sprites.test.js
Labels: pr - good to merge

#4500 Set an initial message number to skip rendering a second time
  src/components/loader/loader.jsx
Labels: performance, pr - needs review

#4498 require text-encoding only if it is needed
  src/lib/default-project/index.js
Labels: performance, pr - needs review

#4485 Sort variable options in "of" block
  src/lib/blocks.js
Labels: pr - good to merge

#4520 Remove prune step from deployment for now
  .travis.yml
Labels: pr - good to merge

#4525 Tag NPM releases
  .travis.yml
Labels: pr - good to merge

#4509 Gif upload v1: sprites, costumes
  package.json
  src/components/sprite-selector/sprite-selector.jsx
  src/components/stage-selector/stage-selector.jsx
  src/containers/costume-tab.jsx
  src/containers/sound-tab.jsx
  src/containers/stage-selector.jsx
  src/containers/target-pane.jsx
  src/lib/file-uploader.js
  src/lib/gif-decoder.js
  test/fixtures/paddleball.gif
  test/integration/backdrops.test.js
  test/integration/costumes.test.js
  test/integration/sprites.test.js
Labels: pr - good to merge

#4410 Delete Preview Modal
  src/components/gui/gui.jsx
  src/components/import-modal/import-modal.css
  src/components/import-modal/import-modal.jsx
  src/components/preview-modal/happy-cat.png
  src/components/preview-modal/preview-modal.css
  src/components/preview-modal/preview-modal.jsx
  src/components/preview-modal/welcome.png
  src/containers/gui.jsx
  src/containers/import-modal.jsx
  src/containers/preview-modal.jsx
  src/lib/app-state-hoc.jsx
  src/lib/hash-parser-hoc.jsx
  src/lib/query-parser-hoc.jsx
  src/playground/render-gui.jsx
  src/reducers/gui.js
  src/reducers/modals.js
  test/integration/backdrops.test.js
  test/integration/backpack.test.js
  test/integration/blocks.test.js
  test/integration/connection-modal.test.js
  test/integration/costumes.test.js
  test/integration/how-tos.test.js
  test/integration/localization.test.js
  test/integration/menu-bar.test.js
  test/integration/project-loading.test.js
  test/integration/sounds.test.js
  test/integration/sprites.test.js
  test/integration/stage-size.test.js
Labels: pr - needs review

#4531 Prompt before file upload replaces project
  src/components/menu-bar/menu-bar.jsx
  src/containers/sb-file-uploader.jsx
  src/lib/shared-messages.js
  test/fixtures/project1.sb3
  test/integration/menu-bar.test.js
Labels: pr - good to merge

#4529 Support isDiscrete sliders
  src/components/monitor-list/monitor-list.jsx
  src/components/monitor/slider-monitor.jsx
  src/containers/monitor.jsx
  test/unit/components/monitor-list.test.jsx
Labels: pr - good to merge

#4528 Put the ask blocks text input above the monitors on the stage.
  src/components/stage/stage.css
  src/css/z-index.css
Labels: pr - good to merge

#4534 Show an "Importing..." alert during file import
  src/containers/costume-tab.jsx
  src/containers/sound-tab.jsx
  src/containers/stage-selector.jsx
  src/containers/target-pane.jsx
  src/lib/alerts/index.jsx
  src/lib/file-uploader.js
  src/reducers/alerts.js
  test/unit/reducers/alerts-reducer.test.js
Labels: pr - needs review

#4555 Fix loading single frame gifs by removing onDone in favor of indices
  src/lib/file-uploader.js
  src/lib/gif-decoder.js
Labels: pr - needs review

#4562 Mouse move drag perf
  src/containers/stage.jsx
Labels: performance, pr - good to merge

#4563 Request a toolbox refresh after switching between tabs to fix #4561
  src/containers/blocks.jsx
  test/integration/blocks.test.js
Labels: pr - needs review

#4567 Add a way for GUI consumer to retrieve snapshots of the stage
  src/lib/project-saver-hoc.jsx
  test/unit/util/project-saver-hoc.test.jsx
Labels: pr - good to merge

#4537 Fixes #4253 by telling the vm the langauge when it is initialized. B…
  src/lib/vm-manager-hoc.jsx
  test/unit/util/vm-manager-hoc.test.jsx
Labels: pr - good to merge
