Repository scratchfoundation/scratch-gui, pull requests merged in 2019-08, with the labels that each got.

#5057 Add Jest-specific linting rules
  package-lock.json
  package.json
  test/.eslintrc.js
  test/helpers/selenium-helper.js
  test/unit/containers/slider-prompt.test.jsx
  test/unit/util/drag-recognizer.test.js
  test/unit/util/project-saver-hoc.test.jsx
Labels: pr - good to merge

#5017 Make delete button accessible
  src/components/delete-button/delete-button.css
  src/components/delete-button/delete-button.jsx
  src/components/sprite-selector-item/sprite-selector-item.jsx
  src/containers/delete-button.jsx
  test/unit/components/__snapshots__/sprite-selector-item.test.jsx.snap
  test/unit/components/sprite-selector-item.test.jsx
Labels: pr - good to merge, touch

#4926 Add play buttons to sound library tiles for touch
  src/components/library-item/lib-icon--sound-rtl.svg
  src/components/library-item/lib-icon--sound.svg
  src/components/library-item/library-item.css
  src/components/library-item/library-item.jsx
  src/components/library/library.jsx
  src/components/play-button/icon--play.svg
  src/components/play-button/icon--stop.svg
  src/components/play-button/play-button.css
  src/components/play-button/play-button.jsx
  src/containers/library-item.jsx
  src/containers/play-button.jsx
  src/containers/sound-library.jsx
Labels: pr - good to merge

#5059 Fix saving after recording a sound
  src/lib/vm-listener-hoc.jsx
  test/unit/util/vm-listener-hoc.test.jsx
Labels: pr - good to merge

#5039 Fix issue where context menu wouldn't come back after dragging
  src/lib/drag-recognizer.js
  test/unit/util/drag-recognizer.test.js
Labels: pr - good to merge

#5076 Revert "Make delete button accessible"
  src/components/delete-button/delete-button.css
  src/components/delete-button/delete-button.jsx
  src/components/sprite-selector-item/sprite-selector-item.jsx
  src/containers/delete-button.jsx
  test/unit/components/__snapshots__/sprite-selector-item.test.jsx.snap
  test/unit/components/sprite-selector-item.test.jsx
Labels: pr - good to merge

#5071 Add webpack resolver to eslintrc so linter doesn't give false positive noUnresolved errors
  package-lock.json
  package.json
  src/.eslintrc.js
Labels: pr - good to merge

#5078 Fix duplicate running blocks by removing pointer-events: none
  src/components/blocks/blocks.css
Labels: pr - good to merge

#5088 Get the mime-type for the file from the blob
  src/lib/download-blob.js
Labels: pr - good to merge

#5092 Close importing after failing to import
  src/containers/target-pane.jsx
Labels: pr - good to merge

#5104 Portuguese and italian
  src/lib/libraries/decks/translate-video.js
Labels: pr - good to merge

#5103 Added the Imagine If video to Imagine If tutorial, and changed last step
  src/lib/libraries/decks/index.jsx
  src/lib/libraries/decks/steps/imagine-choose-sound.en.png
  src/lib/libraries/decks/translate-video.js
Labels: pr - good to merge

#5106 Revert render to last good version
  package-lock.json
  package.json
Labels: critical, pr - needs review

#5134 Fixed Portuguese (Brazilian) locale for tutorial videos
  src/lib/libraries/decks/translate-video.js
Labels: pr - needs review
