Repository scratchfoundation/scratch-gui, pull requests merged in 2019-03, with the labels that each got.

#4618 Update scratch link icon
  src/components/connection-modal/icons/scratchlink.svg
Labels: pr - good to merge

#4621 Add Boost extension "coming soon" tile
  src/lib/libraries/extensions/boost-small.svg
  src/lib/libraries/extensions/boost.png
  src/lib/libraries/extensions/index.jsx
Labels: pr - good to merge

#4627 Run pify package through babel loader.
  webpack.config.js
Labels: pr - good to merge

#4585 fix(css): fix css value has mixed support warning
  src/components/alerts/inline-message.css
  src/components/menu-bar/author-info.css
Labels: pr - needs review

#4589 fix(UI): fix cursor property when hovering account nav items
  src/components/menu/menu.css
  src/components/menu/menu.jsx
Labels: pr - good to merge

#4628 Make the stage color picker work with touch.
  src/containers/stage.jsx
Labels: pr - good to merge

#4568 Slider range change with decimal value support
  src/components/context-menu/context-menu.css
  src/components/context-menu/context-menu.jsx
  src/components/monitor/monitor.jsx
  src/components/slider-prompt/slider-prompt.css
  src/components/slider-prompt/slider-prompt.jsx
  src/components/sprite-selector-item/sprite-selector-item.jsx
  src/containers/monitor.jsx
  src/containers/slider-prompt.jsx
  test/integration/blocks.test.js
  test/unit/containers/slider-prompt.test.jsx
Labels: pr - needs review

#4635 chore(package): update scratch-render to version 0.1.0-prerelease.201…
  package.json
Labels: greenkeeper

#4637 Remove focus selecting in slider prompt
  src/components/slider-prompt/slider-prompt.jsx
  src/containers/slider-prompt.jsx
Labels: pr - needs review

#4638 Remove most of the GA events
  src/components/library/library.jsx
  src/containers/backdrop-library.jsx
  src/containers/controls.jsx
  src/containers/costume-library.jsx
  src/containers/extension-library.jsx
  src/containers/sb-file-uploader.jsx
  src/containers/sound-library.jsx
  src/containers/sprite-library.jsx
Labels: critical, pr - good to merge

#4641 Allow for both bluetooth and internet connection icons in extensions
  src/components/library-item/library-item.css
  src/components/library-item/library-item.jsx
  src/lib/libraries/extensions/index.jsx
Labels: pr - good to merge

#4645 Add telemetry hooks
  src/components/gui/gui.jsx
  src/components/menu-bar/menu-bar.jsx
  src/lib/collect-metadata.js
  src/lib/project-saver-hoc.jsx
  test/unit/util/project-saver-hoc.test.jsx
Labels: pr - good to merge

#4646 Set static asset path (publicPath) with environment var
  webpack.config.js
Labels: pr - good to merge

#4659 Move project saving to server to helper, allow external save action
  src/lib/project-saver-hoc.jsx
  src/lib/save-project-to-server.js
Labels: pr - good to merge

#4657 Refactor extensions library index file
  src/components/connection-modal/auto-scanning-step.jsx
  src/components/connection-modal/connected-step.jsx
  src/components/connection-modal/connecting-step.jsx
  src/components/connection-modal/connection-modal.css
  src/components/connection-modal/connection-modal.jsx
  src/components/connection-modal/error-step.jsx
  src/components/connection-modal/peripheral-tile.jsx
  src/components/connection-modal/scanning-step.jsx
  src/containers/auto-scanning-step.jsx
  src/containers/connection-modal.jsx
  src/containers/scanning-step.jsx
  src/lib/libraries/extensions/boost/boost-small.svg
  src/lib/libraries/extensions/boost/boost.png
  src/lib/libraries/extensions/ev3/ev3-hub-illustration.svg
  src/lib/libraries/extensions/ev3/ev3-small.svg
  src/lib/libraries/extensions/ev3/ev3.png
  src/lib/libraries/extensions/index.jsx
  src/lib/libraries/extensions/makeymakey/makeymakey-small.svg
  src/lib/libraries/extensions/makeymakey/makeymakey.png
  src/lib/libraries/extensions/microbit/microbit-illustration.svg
  src/lib/libraries/extensions/microbit/microbit-small.svg
  src/lib/libraries/extensions/microbit/microbit.png
  src/lib/libraries/extensions/music/music-small.svg
  src/lib/libraries/extensions/music/music.png
  src/lib/libraries/extensions/pen/pen-small.svg
  src/lib/libraries/extensions/pen/pen.png
  src/lib/libraries/extensions/speech2text/speech.png
  src/lib/libraries/extensions/text2speech/text2speech-small.svg
  src/lib/libraries/extensions/text2speech/text2speech.png
  src/lib/libraries/extensions/translate/translate-small.png
  src/lib/libraries/extensions/translate/translate.png
  src/lib/libraries/extensions/videoSensing/video-sensing-small.svg
  src/lib/libraries/extensions/videoSensing/video-sensing.png
  src/lib/libraries/extensions/wedo2/wedo-button-illustration.svg
  src/lib/libraries/extensions/wedo2/wedo-illustration.svg
  src/lib/libraries/extensions/wedo2/wedo-small.svg
  src/lib/libraries/extensions/wedo2/wedo.png
  src/reducers/alerts.js
Labels: pr - good to merge

#4682 Add vernier module to webpack config
  webpack.config.js
Labels: pr - good to merge

#4687 Exclude greenkeeper builds from gh-pages
  .travis.yml
Labels: pr - good to merge

#4688 chore(package): update scratch-vm to latest version
  package.json
Labels: pr - good to merge

#4665 use Collator.compare in place of localeCompare
  src/lib/blocks.js
Labels: performance, pr - good to merge

#4674 dispatch projectChange redux action when project has not changed
  src/lib/vm-listener-hoc.jsx
Labels: performance, pr - good to merge

#4695 update scratch-l10n to latest
  package.json
Labels: localization
