Repository scratchfoundation/scratch-gui, pull requests merged in 2019-07, with the labels that each got.

#4962 Correctly fail on non-200 responses when saving
  src/lib/project-saver-hoc.jsx
  src/lib/save-project-to-server.js
Labels: pr - good to merge

#4794 Add support for custom context menu items for dynamic extension blocks.
  src/lib/define-dynamic-block.js
  test/unit/util/define-dynamic-block.test.js
Labels: pr - good to merge

#4973 Add callback to update dynamic block on workspace.
  src/containers/blocks.jsx
  src/lib/define-dynamic-block.js
  test/unit/util/define-dynamic-block.test.js
Labels: pr - good to merge

#4990 Greenkeeper/scratch paint 0.2.0 prerelease.20190715155430
  package-lock.json
  package.json
Labels: greenkeeper

#4989 Greenkeeper/scratch svg renderer 0.2.0 prerelease.20190715153806
  package-lock.json
  package.json
Labels: greenkeeper

#4983 Move browsers options to .browserslistrc
  .browserslistrc
  webpack.config.js
Labels: pr - good to merge

#4915 Add larger delete icon to make it easier to do on touch devices
  src/components/delete-button/delete-button.css
  src/components/delete-button/delete-button.jsx
  src/components/delete-button/icon--delete.svg
  src/components/sprite-selector-item/sprite-selector-item.css
  src/components/sprite-selector-item/sprite-selector-item.jsx
  test/integration/sprites.test.js
  test/unit/components/__snapshots__/sprite-selector-item.test.jsx.snap
  test/unit/components/sprite-selector-item.test.jsx
  test/unit/containers/sprite-selector-item.test.jsx
Labels: pr - good to merge

#4960 Customize menubar
  src/components/gui/gui.jsx
  src/components/menu-bar/menu-bar.jsx
  src/containers/sb-file-uploader.jsx
Labels: pr - good to merge

#5022 Greenkeeper/scratch l10n 3.5.20190724160319
  package-lock.json
  package.json
Labels: localization

#5023 Update scratch-blocks to version 0.1.0-prerelease.1563990552
  package-lock.json
  package.json
Labels: greenkeeper, pr - good to merge

#5026 Check for null child before cloning menu item
  src/components/menu/menu.jsx
Labels: pr - good to merge

#5027 Remove touch slop
  src/components/delete-button/delete-button.css
Labels: pr - good to merge

#5021 Support for variables extension - Variable Renaming Context Menu
  src/containers/blocks.jsx
  src/lib/define-dynamic-block.js
  test/unit/util/define-dynamic-block.test.js
Labels: pr - good to merge

#4974 Sound editor update: selection-based editing
  package.json
  src/components/asset-panel/asset-panel.css
  src/components/audio-trimmer/audio-selector.jsx
  src/components/audio-trimmer/audio-trimmer.css
  src/components/audio-trimmer/audio-trimmer.jsx
  src/components/audio-trimmer/icon--handle.svg
  src/components/audio-trimmer/playhead.jsx
  src/components/audio-trimmer/selection-handle.jsx
  src/components/icon-button/icon-button.css
  src/components/icon-button/icon-button.jsx
  src/components/sound-editor/icon--copy-to-new.svg
  src/components/sound-editor/icon--copy.svg
  src/components/sound-editor/icon--delete.svg
  src/components/sound-editor/icon--fade-in.svg
  src/components/sound-editor/icon--fade-out.svg
  src/components/sound-editor/icon--lounder.svg
  src/components/sound-editor/icon--mute.svg
  src/components/sound-editor/icon--paste.svg
  src/components/sound-editor/icon--play.svg
  src/components/sound-editor/icon--stop.svg
  src/components/sound-editor/sound-editor.css
  src/components/sound-editor/sound-editor.jsx
  src/components/waveform/waveform.jsx
  src/containers/audio-selector.jsx
  src/containers/audio-trimmer.jsx
  src/containers/record-modal.jsx
  src/containers/sound-editor.jsx
  src/lib/audio/audio-effects.js
  src/lib/audio/audio-util.js
  src/lib/audio/effects/echo-effect.js
  src/lib/audio/effects/fade-effect.js
  src/lib/audio/effects/mute-effect.js
  src/lib/audio/effects/robot-effect.js
  src/lib/audio/effects/volume-effect.js
  test/__mocks__/audio-effects.js
  test/integration/sounds.test.js
  test/unit/components/__snapshots__/sound-editor.test.jsx.snap
  test/unit/components/sound-editor.test.jsx
  test/unit/containers/sound-editor.test.jsx
  test/unit/util/audio-effects.test.js
Labels: pr - good to merge

#5048 Update fade icons
  src/components/sound-editor/icon--fade-in.svg
  src/components/sound-editor/icon--fade-out.svg
Labels: pr - needs review

#5049 Remove test.only
  test/integration/sounds.test.js
Labels: pr - good to merge
