Repository scratchfoundation/scratch-gui, pull requests merged in 2019-11, with the labels that each got.

#5277 Include library JSON files in package distribution
  webpack.config.js
Labels: pr - good to merge

#5274 Greenkeeper/scratch l10n 3.6.20191029224007
  package-lock.json
  package.json
Labels: greenkeeper, pr - needs review

#5258 Greenkeeper/scratch vm 0.2.0 prerelease.20191018142546
  package-lock.json
  package.json
Labels: pr - needs work

#5205 Trim some unused config from the Travis config
  .travis.yml
Labels: pr - good to merge

#5305 Reorder tutorials for HOC 2019
  src/lib/libraries/decks/index.jsx
Labels: pr - good to merge
