Repository scratchfoundation/scratch-gui, pull requests merged in 2019-05, with the labels that each got.

#4784 Fix auto-save when clicking See Project Page
  src/components/menu-bar/confirm-replace-hoc.jsx
  src/components/menu-bar/menu-bar.jsx
  src/containers/menu-bar-hoc.jsx
  test/unit/containers/menu-bar-hoc.test.jsx
Labels: pr - needs review

#4785 Enable the boost extension
  src/lib/libraries/extensions/index.jsx
Labels: pr - good to merge

#4775 chore(package): update chromedriver to version 74.0.0
  package.json
Labels: greenkeeper

#4792 chore(package): update scratch-vm to version 0.2.0-prerelease.2019043…
  package.json
Labels: greenkeeper

#4793 chore(package): update scratch-l10n to version 3.2.20190501144004
  package.json
Labels: greenkeeper

#4664 replace Blocks.utils.is3dSupported with constant value function
  src/lib/blocks.js
Labels: performance, pr - good to merge

#4786 Update eslint-plugin-react and fix newly discovered lint errors.
  package.json
  src/components/menu-bar/menu-bar.jsx
  src/containers/stage.jsx
  src/lib/app-state-hoc.jsx
  src/lib/project-fetcher-hoc.jsx
  src/lib/project-saver-hoc.jsx
  src/lib/vm-listener-hoc.jsx
  src/lib/vm-manager-hoc.jsx
Labels: pr - good to merge

#4731 Add shrink/expand and new fencing feature to tutorial cards
  src/components/cards/card.css
  src/components/cards/cards.jsx
  src/components/cards/icon--close.svg
  src/components/cards/icon--expand.svg
  src/components/cards/icon--shrink.svg
  src/containers/cards.jsx
  src/reducers/cards.js
  src/reducers/gui.js
Labels: pr - good to merge

#4806 Surprise sprite button does not give you letters
  src/containers/target-pane.jsx
Labels: pr - good to merge

#4677 render only new toolbox xmls
  src/containers/blocks.jsx
Labels: performance, pr - good to merge

#4800 Delay loading and rendering gui
  src/components/gui/gui.jsx
  src/containers/gui.jsx
Labels: performance, pr - good to merge

#4841 add timeouts & messages to all driver.wait calls
  test/helpers/selenium-helper.js
Labels: pr - good to merge, testing

#4835 Pause video on tutorial window shrink
  src/components/cards/card.css
  src/components/cards/cards.jsx
Labels: pr - good to merge

#4846 Update the built-in SVG assets for the default project
  src/lib/default-project/09dc888b0b7df19f70d81588ae73420e.svg
  src/lib/default-project/3696356a03a8d938318876a593572843.svg
  src/lib/default-project/b7853f557e4426412e64bb3da6531a99.svg
  src/lib/default-project/e6ddc55a6ddd9cc9d84fe0b4c21e016f.svg
  src/lib/default-project/index.js
  test/unit/util/default-project.test.js
Labels: pr - needs review

#4871 Stabilize integration tests
  test/helpers/selenium-helper.js
  test/integration/examples.test.js
  test/integration/menu-bar.test.js
  test/integration/project-loading.test.js
Labels: pr - good to merge, testing
