Repository scratchfoundation/scratch-gui, pull requests merged in 2020-09, with the labels that each got.

#6116 Force LTR on drag-layer
  src/components/drag-layer/drag-layer.css
Labels: localization, pr - needs review, priority 3

#6152 Fix logic for when to run deploy-gh-pages
  .circleci/config.yml
Labels: pr - good to merge

#6130 Move src/* dependencies into `dependencies`
  package-lock.json
  package.json
Labels: developer facing, pr - good to merge

#6162 Added Getting Started video in 7 languages
  src/lib/libraries/decks/translate-video.js
Labels: pr - good to merge

#6156 Add translation push cron job to circle.
  .circleci/config.yml
Labels: pr - good to merge

#6140 Have circle deploy to the standard npm tags instead of travis.
  .circleci/config.yml
  .travis.yml
Labels: pr - good to merge

#6176 Change end-of-tutorial links for several tutorials
  src/lib/libraries/decks/index.jsx
Labels: pr - good to merge

#6195 Remove Travis config since we're using circle
  .travis.yml
Labels: pr - good to merge

#6127 Localize backpack item label
  src/components/backpack/backpack.jsx
Labels: localization, pr - needs review, priority 2

#6220 Fixed 2 steps in Animate a Name
  src/lib/libraries/decks/steps/name-grow.en.png
  src/lib/libraries/decks/steps/name-spin.en.png
Labels: pr - good to merge
