Repository scratchfoundation/scratch-gui, pull requests merged in 2020-05, with the labels that each got.

#5516 Add clickBlocksCategory integration test helper function
  test/helpers/selenium-helper.js
  test/integration/blocks.test.js
Labels: pr - good to merge

#5101 Allow some kind of downloading to work on iOS Safari
  src/lib/download-blob.js
Labels: pr - good to merge, pr - needs work

#5731 Add new people sprites
  src/lib/libraries/costumes.json
  src/lib/libraries/sprites.json
Labels: pr - good to merge

#5278 Don't align-items: center in stage-overlay-content
  src/components/stage/stage.css
Labels: pr - good to merge

#5164 Emit projectDidSave for all types of saves, not just file exports
  src/lib/project-saver-hoc.jsx
Labels: pr - good to merge

#5558 fix costume animation in sprite library
  src/components/library/library.jsx
  src/components/scratch-image/scratch-image.jsx
  src/containers/library-item.jsx
Labels: pr - good to merge

#5451 add hook on telemetry dialog for displaying privacy policy
  src/components/gui/gui.jsx
  src/components/telemetry-modal/telemetry-modal.jsx
Labels: pr - good to merge

#5643 Omit componentRef from DropAreaHOC's passed props
  src/lib/drop-area-hoc.jsx
Labels: pr - good to merge

#5434 Add about menu button
  .gitattributes
  package.json
  src/components/gui/gui.jsx
  src/components/menu-bar/icon--about.svg
  src/components/menu-bar/menu-bar.css
  src/components/menu-bar/menu-bar.jsx
  test/__mocks__/editor-msgs-mock.js
  test/unit/components/menu-bar.test.jsx
Labels: High Impact, High Severity, pr - good to merge

#4916 Add pointer-events to alert container CSS
  src/components/alerts/alert.css
  src/components/gui/gui.css
Labels: Low Impact, Medium Severity, pr - needs review
