Repository scratchfoundation/scratch-gui, pull requests merged in 2020-08, with the labels that each got.

#5974 Fix backpacking zero-height/width costumes
  src/lib/backpack/jpeg-thumbnail.js
Labels: priority 2

#6021 Make SortableHOC work properly in RTL mode
  src/lib/drag-utils.js
  src/lib/sortable-hoc.jsx
  test/unit/util/drag-utils.test.js
Labels: pr - good to merge, priority 3

#4542 Position blocks added from "share the love" within the viewport
  src/containers/blocks.jsx
  src/containers/target-pane.jsx
  src/lib/layout-constants.js
  src/reducers/gui.js
  src/reducers/workspace-metrics.js
  test/unit/reducers/workspace-metrics-reducer.test.js
Labels: pr - good to merge, priority 3

#6123 Step toward GUI migration to circle: have circle deploy to npm
  .circleci/config.yml
Labels: pr - good to merge

#5877 Add assets to editingTarget at the time it started uploading
  src/containers/costume-tab.jsx
  src/containers/sound-tab.jsx
Labels: pr - good to merge, priority 3

#6131 Deploying to gh-pages from circle instead of Travis
  .circleci/config.yml
  .travis.yml
Labels: pr - good to merge
