Repository scratchfoundation/scratch-gui, pull requests merged in 2020-11, with the labels that each got.

#6354 Added Getting Started video in 19 languages for Phase 2
  src/lib/libraries/decks/translate-video.js
Labels: localization, pr - good to merge

#6230 Remove autofocus from question input
  src/components/question/question.jsx
Labels: pr - good to merge, pr - needs review

#5482 Ignore sound editor keyboard shortcut on fullscreen stage
  src/containers/sound-editor.jsx
  test/unit/containers/sound-editor.test.jsx
Labels: pr - good to merge, priority 3

#6177 Update default project assets
  package-lock.json
  src/lib/default-project/0fb9be3e8397c983338cb71dc84d0b25.svg
  src/lib/default-project/b7853f557e4426412e64bb3da6531a99.svg
  src/lib/default-project/bcf454acf82e4504149f7ffe07081dbc.svg
  src/lib/default-project/e6ddc55a6ddd9cc9d84fe0b4c21e016f.svg
  src/lib/default-project/index.js
  src/lib/default-project/project-data.js
Labels: pr - needs review

#6273 Handle user picked peripheral
  src/containers/scanning-step.jsx
Labels: pr - good to merge
