Repository scratchfoundation/scratch-gui, pull requests merged in 2020-07, with the labels that each got.

#5962 disable webpack progress plugin on CI
  package.json
  webpack.config.js
Labels: developer facing, ergonomics, pr - good to merge

#5397 initialize Google Analytics only if GA_ID is set
  src/lib/analytics.js
Labels: pr - good to merge, priority 3

#5996 add troubleshooting section to README
  README.md
Labels: pr - needs review

#5513 Extract dragged sprites' drawables in screen space
  src/containers/stage.jsx
Labels: blocked, pr - good to merge

#6038 Get unittests and integration tests (consistently?) passing on circle again.
  .circleci/config.yml
Labels: pr - good to merge

#6045 revert version of scratch-paint to remove outline gradient
  package-lock.json
  package.json
Labels: pr - needs review
