Repository scratchfoundation/scratch-gui, pull requests merged in 2020-03, with the labels that each got.

#5492 Bump scratch-blocks and scratch-l10n versions for release
  package-lock.json
  package.json
Labels: pr - good to merge

#5491 unflakify four blocks integration tests
  test/integration/blocks.test.js
Labels: pr - good to merge

#5362 refactor onLoadedProject() creator to handle success==false consistently; add tests of project state action creators
  src/reducers/project-state.js
  test/unit/reducers/project-state-reducer.test.js
  test/unit/util/project-saver-hoc.test.jsx
Labels: pr - good to merge

#5532 Enhance mysterious atmosphere
  package.json
  src/components/mystery-mode/mystery-mode.css
  src/containers/stage.jsx
Labels: pr - needs review

#5540 Greenkeeper/scratch l10n 3.8.20200325112845
  package-lock.json
  package.json
Labels: localization

#5541 Greenkeeper/scratch blocks 0.1.0 prerelease.1585138708
  package-lock.json
  package.json
Labels: localization
