Repository scratchfoundation/scratch-gui, pull requests merged in 2020-06, with the labels that each got.

#5704 Remove box-sizing: content-box from sprite highlight box CSS
  src/components/stage/stage.css
Labels: pr - good to merge

#5861 Stop building gh pages branches for dependabot
  .travis.yml
Labels: pr - good to merge

#5867 Update contributor guidelines
  .github/CONTRIBUTING.md
Labels: pr - good to merge

#5885 Update localization test
  package-lock.json
  package.json
  test/integration/localization.test.js
Labels: pr - good to merge

#5826 Pass current editing target to getBlocksXML
  src/containers/blocks.jsx
Labels: blocked, pr - good to merge

#5510 Call renderer.draw immediately on drag start/stop
  src/containers/stage.jsx
Labels: pr - good to merge

#5740 Fix sprite tile highlight color on Edge
  src/css/colors.css
Labels: pr - good to merge

#5463 Fix default parameter text loading in English
  src/containers/blocks.jsx
  src/lib/make-toolbox-xml.js
  test/integration/localization.test.js
Labels: pr - good to merge

#5508 Refactor stage layout
  src/components/gui/gui.css
  src/components/gui/gui.jsx
  src/components/stage-wrapper/stage-wrapper.css
  src/components/stage-wrapper/stage-wrapper.jsx
  src/components/stage/stage.css
  src/components/stage/stage.jsx
  src/containers/green-flag-overlay.jsx
Labels: pr - needs review, priority 3

#5927 Prevent crash when saving locally on iOS 13 safari
  src/lib/download-blob.js
Labels: pr - good to merge

#5934 Reorder tutorials to their order pre-HOC
  src/lib/libraries/decks/index.jsx
Labels: pr - good to merge
