Repository scratchfoundation/scratch-gui, pull requests merged in 2021-01, with the labels that each got.

#6262 Pass svg-renderer function to Paint
  src/containers/paint-editor-wrapper.jsx
Labels: pr - needs review

#6553 Merge release 1/7/2021
  package-lock.json
  package.json
  src/components/target-pane/target-pane.jsx
  src/containers/monitor.jsx
  src/containers/sound-editor.jsx
  src/lib/default-project/0fb9be3e8397c983338cb71dc84d0b25.svg
  src/lib/default-project/b7853f557e4426412e64bb3da6531a99.svg
  src/lib/default-project/bcf454acf82e4504149f7ffe07081dbc.svg
  src/lib/default-project/e6ddc55a6ddd9cc9d84fe0b4c21e016f.svg
  src/lib/default-project/index.js
  src/lib/default-project/project-data.js
  src/lib/libraries/decks/translate-image.js
  src/lib/libraries/decks/translate-video.js
  test/integration/costumes.test.js
  test/unit/containers/sound-editor.test.jsx
Labels: pr - needs review

#5450 Revert "Revert "refactor SB* file uploader into top-level HOC""
  src/components/gui/gui.jsx
  src/components/menu-bar/menu-bar.jsx
  src/containers/gui.jsx
  src/containers/sb-file-uploader.jsx
  src/lib/sb-file-uploader-hoc.jsx
  test/integration/menu-bar.test.js
  test/integration/sb-file-uploader-hoc.test.js
  test/unit/containers/sb-file-uploader.test.jsx
  test/unit/util/sb-file-uploader-hoc.test.jsx
Labels: pr - good to merge

#5662 Close Importing when the sound is invalid
  src/containers/sound-tab.jsx
  src/lib/file-uploader.js
Labels: pr - good to merge, priority 3

#6463 About menu
  src/components/gui/gui.jsx
  src/components/menu-bar/menu-bar.jsx
  src/components/telemetry-modal/telemetry-modal.css
  src/components/telemetry-modal/telemetry-modal.jsx
  src/lib/app-state-hoc.jsx
  src/reducers/menus.js
Labels: pr - good to merge
