Repository scratchfoundation/scratch-gui, pull requests merged in 2022-02, with the labels that each got.

#4147 Automatically update flyout checkboxes
  src/containers/blocks.jsx
Labels: pr - good to merge, priority 4

#4148 "Hide" monitor context menu option
  src/components/monitor/monitor.jsx
  src/containers/monitor.jsx
  test/helpers/selenium-helper.js
  test/integration/blocks.test.js
Labels: pr - good to merge

#7971 Make the hide option on monitors a bordered menu item
  src/components/monitor/monitor.jsx
Labels: blocked
